saving-satoshi/saving-satoshi

app/chapters/[slug]/genesis/code.tsx, app/chapters/[slug]/genesis/info.tsx, app/chapters/[slug]/genesis/layout.tsx, app/chapters/[slug]/genesis/page.tsx, package.json
This PR introduces a tabbed layout on mobile where the user can switch between seeing the lesson info or code. Both at once can only be seen on desktop (no tabs there).
👳🏻[Check the preview](https://saving-satoshi-git-feature-genesis-respon-44c3c2-saving-satoshi.vercel.app/chapters/chapter-1/genesis)👲🏻
- Adds the 'react-responsive' module to more easily handle screen-size specific layouts
- Adds tabs to the genesis page on mobile only
- Splits up the genesis lesson into sub-components so they can be individually shown and hidden based on which tab is selected
- Lots of style tweaks to more closely match the Figma file
Designs:
It's a very common thing to show slightly different UI on mobile and desktop, but it seems to take a lot of extra code overhead to do this. First we need the …
=> Add tabs to genesis lesson on mobile

components/ui/BoxButton.tsx, components/ui/Tooltip.tsx, styles/globals.css
Chapters have unique background colors that get picked up by certain UI elements. This PR introduces a basic system using a `back` (= background) variable that gets changed by appending a theme class to the current page. Related to [this comment](https://github.com/saving-satoshi/saving-satoshi/pull/37#discussion_r1060170784).
Themes also include a background pattern, which is not included here. Something to add separately, we need to figure out the best way (optimizing file size and a fade on load) to implement this.
Here's a mock-up with an example of how the theme is expressed. See how the label on the button picks up the background color. Not that this is not needed in many places and it's fine to just overlay white or black with some opacity.
PR #37 includes various hardcoded color …
=> Introduce themes using CSS variables

content/pages/about.mdx, contentlayer.config.ts
Next complains that the about page does not have a defined type. Looks like the type existed in the contentlayer config, but was not added correctly. Fixing this here.
=> Minor code fix for the about page

app/chapters/[slug]/genesis/code.tsx, app/chapters/[slug]/genesis/genesis-pt2/page.tsx, app/chapters/[slug]/transacting/transacting-1/page.tsx, app/chapters/[slug]/transacting/transacting-2/page.tsx, components/chapters/FindChallengeBottomBar.tsx, public/assets/icons/check.svg
Fixes #70
Fixes #59
This PR adds a `FindChallengeBottomBar` that now handles the input validation with the props `input` and `expected`. I think it makes the user input validation flow easier.
=> Add FindChallengeBottomBar and refactor challenges validation

components/chapters/LoginModal.tsx, components/chapters/SignUpModal.tsx, components/ui/NavBar.tsx
This logic was not properly working before, so users could not smoothly sign up, log out, back in, clear progress, etc.
**How to test:**
Sign up, log out, log back in, log back out, and then clear your user data again.
1. Clear your local storage (`user` and `loggedIn` items)
2. Go to the home page
3. Click account button in the top-right corner
4. In the sign-up modal, pick an avatar, copy your code and click the button at the bottom to close it
5. The account button in the nav bar should now should your avatar
6. Click it again to see the login modal stating that you are logged in
7. Click "Sign out"
8. The account button in the nav bar should now should the outline icon again
9. Click it again to see the login modal in the login state
10. Log in with the code you copied previously
11. …
=> Fix signup, login and logout logic in the NavBar

app/chapters/[slug]/genesis/genesis-pt2/page.tsx, app/chapters/[slug]/transacting/transacting-2/page.tsx, components/Hero.tsx, components/chapters/LoginModal.tsx, components/chapters/SignUpModal.tsx, components/ui/BoxButton.tsx, components/ui/Tooltip.tsx, styles/globals.css, tailwind.config.js
Both styles are needed for the copy button in the Signup modal.
Learned a bit about Tailwind here that results in some tweaks. To get opacity with color variables, there needs to be a color transform function in the Tailwind config, so I added that. This way we also don't need to use color variables in Tailwind classes anymore, as the transform adds those.
Also replaced two existing color definitions with our new variable-based ones.
=> Adding green and tiny styles to the BoxButton

app/chapters/[slug]/page.tsx, components/chapters/ChaptersNavbar.tsx, components/templates/ChapterIntro/ChapterIntroLayout.tsx, tailwind.config.js
Resolved #64 
Template for Chapter Intro page. Changed https://github.com/saving-satoshi/saving-satoshi/blob/master/components/chapters/ChaptersNavbar.tsx#L13 `w-screen` to `w-full` as it was causing horizontal scrolling.
Props required:
- `slug`: for fetching Intro data
- `Next`: link to the next part of the chapter
Screenshot:
=> Template for Chapter Intro

app/about/page.tsx, app/chapters/page.tsx, components/ui/Footer.tsx, components/ui/NavBar.tsx
Fixes #99 
Changed `w-screen` to `w-full` to fix the horizontal Scrolling issue on the Chapters and About pages.
Screenshots:
Before:
Now:
Before:
Now:
=> Horizontal Scrolling fix for Chapters and About page

.github/workflows/ADD_ISSUES_TO_PROJECT.yml
Tested it on my own repo this time which I realize now I should've done at the beginning instead of creating so much noise. Apologies. Won't make the same mistake again.
Fix was to add specific version #. It's g2g.
=> Final PR for issue to project

.commitlintrc.json, .eslintrc.json, .gitignore, .husky/commit-msg, .husky/pre-commit, package.json, yarn.lock
We haven't discussed this, but I think setting up a precommit hook to format files will help make sure the code is formatted consistently in the codebase. Feel free to let me know if any of you don't want this tooling in place for some reason.
This PR also makes sure every dev runs the `husky install` command by running it as a `postinstall` script. I noticed that setting up husky enforces conventional commits. I think that's because the `@commitlint/config-conventional` package is installed.
=> chore: automate code formatting

.gitignore, .vscode/settings.json, content/lessons/genesis/genesis-2.tsx, content/lessons/transacting/transacting-2.tsx, ui/lesson/Lesson.tsx, ui/lesson/Terminal.tsx, ui/lesson/TerminalChallenge.tsx, ui/lesson/index.ts
Fixes #67, Fixes #68 
- Created a Template for Terminal-based Challenges
- Implemented the template for Chapter 1, challenge 1, part 2 and Chapter 1, challenge 2, part 2
- Props required by the template 
- `expectedInput` : answer to the challenge problem
- `saveInfo` : information required for saving user progress
- `next` : link to next part of chapter
- `instruction` : terminal instruction for user
- `successMessage` : Message displayed to the user upon finishing a challenge
Screenshots:
=> Template for Terminal Challenge

ui/common/Input.tsx
Fixes #154 
Added max width of the screen to prevent any input from extending beyond the screen size.
[iPhone input screenshot](https://user-images.githubusercontent.com/108441023/219769902-41700422-ce19-4a81-8913-f1794cef8149.PNG)
[Input Preview](https://saving-satoshi-git-fork-benalleng-safariwidth-savingsatoshi.vercel.app/en/chapters/chapter-1/genesis-1)
With just an iPhone some more testing may be needed on a Mac but this particular safari bug seems to be solved
Tested on
Safari (iPhone)
Chrome (Windows)
firefox (Android)
=> Input Area Max-width

ui/introduction/Introduction.tsx
Closes https://github.com/saving-satoshi/saving-satoshi/issues/166
This problem was a little more involved than i first anticipated but only because we are using the component from next.js and not a standard html tag. Once i realized this there is clear documentation on how to utilize the parameters to get it to behave how we expect it to.
[Preview](https://saving-satoshi-git-fork-benalleng-chapter-67b81e-saving-satoshi.vercel.app/en/chapters/chapter-1)
=> Chapter intro page Scroll

ui/lesson/TerminalChallenge.tsx
This PR should close #197. Added some logic that removes `\t`, `\r` and `\n` from the input before it compares it with the `expectedInput`.
=> Sanitize input before checking if valid for Terminal challenges

content/lessons/genesis/genesis-2/translations.ts
This is a request by jonas to swap out the link to the bitcoin wiki.
=> Replace btcmag link with bitcoin wiki

lib/translate.tsx
Closes #218
now tooltips have a cursor pointer baked in, no need to add it to the translation
=> Add pointer to Tooltips

content/lessons/transacting/transacting-2/index.tsx, content/lessons/transacting/transacting-3/index.tsx, content/lessons/transacting/transacting-3/translations.ts
Resolves #185 
- This PR replaces the transaction from `75764fd0c95b4c17b728d10f7555509adfc0789ddc47683c45aeddd1c34727f8` to `ee3b8caaeb58245338dd299467de89ec6833d2a4235493c95059934603b5e98d` in both parts of Chapter-1, Challenge-2.
- I have removed the following part from the success message.
```
...We don’t know why tacos were so important to the anonymous sender of this transaction, but here we are.
And it’s an admirable goal at least.
```
- This can later be replaced with a more appropriate success message.
=> Changed the transaction in Chapter-1, Challenge-2

app/[lang]/chapters/[slug]/[lesson]/layout.tsx, ui/lesson/Info.tsx, ui/lesson/Lesson.tsx, ui/lesson/Terminal.tsx
Replacing grid with flex layout to fix a few issues. Also removing some unnecessary Tailwind tags.
Should fix issue #214 and the problem pointed out in this comment: https://github.com/saving-satoshi/saving-satoshi/pull/146#issuecomment-1450874989
I'd recommend avoiding grid in favor of flex box. I only saw it in a few places in the codebase and on those a grid wasn't even used (meaning multiple rows and columns), but it's either a row a column. Safari follows an older spec in regards to height calculation, which caused one of the layout issue mentioned above.
Overall I also see a lot of unnecessary layout tags that have no effect. I wonder if everyone is clear on exactly how flexbox works. If not, I recommend [this guide](https://css-tricks.com/snippets/css/a-guide-to-flexbox/).
**[Live …
=> Fixes a few layout issues in lesson screens

components/Topbar.tsx
Now that our homepage doesn't need the `/en` in the url this can be removed when clicking the home-button in the TopBar for consistency
=> Remove lang param from home-button

middleware.ts
Fixes #222 (testing)
In firefox favicon and android-icon are being redirected to `/en
=> Fix: 404 for favicon and android-icon

hooks/useMediaQuery.ts
Closes #264
when run locally the server no longer issues an error stating that the window is undefined.
=> Ensure window is defined for useMediaQuery

components/Navbar/UserButton.tsx
Closes #270
a refresh no longer causes page shifting on 
https://saving-satoshi-git-fork-benalleng-fixuserbutton-saving-satoshi.vercel.app/
the svg still lags but the Navbar no longer shifts
=> Add height to modal to remove page shifting on refresh

i18n/locales/en.ts
In chapter 1, challenge 2, there are explicit instructions to open up the transaction details (see instruction number 2):
However, the link we provide already has the details opened up. There are two ways we can smooth this out:
1. Remove instruction number 2 and don't tell the user to expand the details
2. Don't expand the transaction details for the user and have them do it themselves
I like the idea of not expanding the transaction details for the user because it teaches them that you can open transactions up and take a look inside :smile:. But I acknowledge that all block explorers are different and there are pro's to the other option of just having less instructions. Happy to go either way on this!
=> Chapter 1, Challenge 2: Tweak block explorer link

content/lessons/chapter-1/transacting-3.tsx, i18n/locales/en.ts
closes #309
base on the issue there was only exact changes for transacting-3 but i tried my best to have good copy that made no mention of direction of desktop or mobile specific pointers. i went with "code block" as i believe that still directs the user to press the code tab button after reading this, but I believe that "code tab" could work if not trying even more to remove any directional pointers in the copy
genesis-2
genesis-3
transacting-2
transacting-3
I am not sure if the copy changes go far enough in some cases, I had thought about simply saying copy "and paste" the value you found. and maybe try to make the code tab button more noticeable.
=> Make device agnostic copy in Ch. 1

app/[lang]/chapters/[slug]/[lesson]/page.tsx, components/Client.tsx, components/ClientOnly.tsx
This PR fixes #445 by only rendering the `<head>` client-side. To accomplish this I added a `<Client>` component that we can use to wrap around other elements which should only render on the client-side.
=> Only render dynamic <head> client-side for lesson page

i18n/locales/en.ts
Tooltip error found in QA in #460
[Preview](https://saving-satoshi-git-fork-benalleng-issue460-b5d4f9-savingsatoshi.vercel.app/en/chapters/chapter-2/hashing-4?dev=true)
=> Add secondaryTheme to tooltip hints in CH2

providers/ProgressProvider.tsx
Closes #456
This adds a check to make sure that the user is only saving their progress on new progress steps and not if they go back through the lessons.
=> Change progress logic to only save progress on advancement

app/[lang]/chapters/[slug]/[lesson]/page.tsx, content/lessons/chapter-2/scripting-2.tsx, providers/ProgressProvider.tsx, ui/lesson/HashChallenge.tsx, ui/lesson/ScriptingChallenge/index.tsx
Closes #457
This makes the redirect for locked lessons work only at the very end of the progress so a user should be allowed to freely roam around once they have completed a particular lesson
=> New redirect logic to check for user progress

components/Navbar/NavbarDesktop/NavbarDesktop.tsx, components/Navbar/NavbarMobile/NavbarMobile.tsx, hooks/useSaveAndProceed.ts, hooks/useSaveAndReturn.ts, lib/progress.ts
This PR addresses part-1 of #480 
> Auto-save progress at the end of the chapter. Make it reusable so we can continue to add it as we add more chapters.
<h3>Description:</h3>
Once the user reaches the final outro of the page and has created an account earlier, this PR allows the progress to be updated to the next chapter's intro page.
This PR also updates the relevant code to be directed to the correct chapter's tag on the chapter selection screen.
=> Auto save progress at the end of Chapter

content/lessons/chapter-1/outro-2.tsx, content/lessons/chapter-2/outro-1.tsx, content/lessons/chapter-3/outro-1.tsx, ui/chapter/DesktopEnd.tsx, ui/chapter/End.tsx, ui/chapter/MobileEnd.tsx
This is the second and final PR
Resolves #480
This PR Introduces the new MobileEnd.tsx, which creates a separate layout for outro pages on Mobile devices.
This PR also removes the fixed page height from the chapter-2 and chapter-3 outro pages.
=> Introduce MobileEnd.tsx

content/lessons/chapter-3/pool-1.tsx, content/lessons/chapter-3/solo-1.tsx, types/index.ts, ui/common/ContributionBar.tsx, ui/common/Profile.tsx
Follow-up PR for #534
Further improvements I think we can make in a separate PR:
- Render the avatars on a different place in the markup so that the `overflow-hidden` doesn't cut them off when the block amount is low.
=> Contribution bar improvements

app/[lang]/chapters/page.tsx
simple bg color change for the footer to contrast the bg of the chapters page, adds opacity instead of using a different blue
Old:
New:
=> Change footer color on chapters page to match main background

content/lessons/chapter-3/coop-2.tsx
Closes #585 
in CH3COO2 only one miner is supposed to find blocks based on the nonce overlap. I created a semi-hacky way of leaving the other miners to be visible while still giving the correct number fo blocks to the protagonists / antagonists.
=> Remove blocks from other miners in CH3COO2

app/[lang]/chapters/[slug]/[lesson]/page.tsx, content/lessons/chapter-3/coop-1.tsx, hooks/useEnvironment.ts, hooks/useSaveAndProceed.ts, ui/chapter/Chapter.tsx
This PR resolves #600 so we can use `?dev=true` to bypass feature flags on the `/en/chapters` page, and it makes sure that the `?dev=true` query param will be passed along to lessons.
=> Bypass feature flags using dev query param

ui/common/StatusBar.tsx
The status bar was cut off on mobile because a fixed height was applied indiscriminately via "h-14". Only the top part of the button was visible. This is only supposed to the fixed on desktop, so I changed it to "md:h-14".
I also put the check mark into a round green circle to match the design. We changed this a while back to make the success state more noticeable.
Peace & happiness.
=> StatusBar tweaks

ui/common/StatusBar.tsx
Fixes an error where the status bar has a div as a child of a p element, which is not allowed
=> StatusBar div-child-of-p error

content/lessons/chapter-1/intro-2.tsx, content/lessons/chapter-2/intro-1.tsx, content/lessons/chapter-2/intro-2.tsx, content/lessons/chapter-3/intro-1.tsx, content/lessons/chapter-3/split-1.tsx, content/lessons/chapter-4/intro-1.tsx, content/lessons/chapter-5/intro-1.tsx, content/lessons/chapter-5/intro-2.tsx, content/lessons/chapter-5/intro-3.tsx
Various images were cut off weirdly at various screen sizes. Reason is that our layouts provide specific aspect ratios. We instruct the browser to fill the available area with the images. The browser needs to decide how to crop and center them in the given area. With this update, we now use the object position CSS property to provide specific points of interest in each image. Basically like a coordinate in the image that should be visible as much as possible. I looked at each image and calculated the coordinates (defined as percentages in Tailwind).
I removed the media query logic because it's not needed. Just by defining the point of interest in the image, the browser can figure out the cropping.
Example of a before and after.
📸[Check the …
=> Adjust object position for intro component images

ui/lesson/Info.tsx
This PR closes  #758  for some weird reason sm:px-12 was missing, although i did check production to compare both instances
Production code
=> Added padding back to terminal challenges

content/lessons/chapter-4/address-2.tsx, content/lessons/chapter-4/public-key-3.tsx, content/lessons/chapter-4/public-key-4.tsx, content/resources/chapter-4/public-key.tsx, i18n/locales/en.ts
Closes #784 
- Fixes the python and javascript validation for public-key-4 and address 2
- Fixes the private key object  in private-key-3 to be parsed properly 
- Changes the expected answer copy to ask for a hex string instead of bytes
[Preview](https://saving-satoshi-git-fork-benalleng-issue784-savingsatoshi.vercel.app/en/chapters/chapter-4/public-key-3?dev=true)
=> Fix public key and address 2 validation

i18n/README.md
Adding a / at the beginning incorrectly implies a root directory rather than the repository root, which can lead to unintended paths when using commands like cd or opening with an editor.
=> Remove extra slash in README

content/lessons/chapter-6/put-it-together-5.tsx, types/index.ts, types/interfaces.ts, ui/lesson/ScriptingChallenge/Editor.tsx, ui/lesson/ScriptingChallenge/index.tsx
The intention here is to be able to provide range blocks to fold in the editor.  Unfortunately the ability to pass in ranges to the fold function in the editor is currently broken in the version we are using.  As a workaround I'm using the `foldAllExcept` action instead.  This means that for now it only supports one element in the `rangesToCollapse` array but we should revisit this once the [fix](https://github.com/microsoft/vscode/pull/201315) is available in the [editor](@monaco-editor/react
) we are using.
=> feat: Added ability to fold code on load

content/lessons/chapter-2/scripting-2.tsx, content/resources/chapter-2/scripting.tsx
Closes #547
With our better understanding of the possiblity for test vectors in our repl environment I enhanced our scripting 2 challenge to better prevent cheating and hopefully allows for more reliable results
try returning a string of length 64 that is all zeroes like 
```
return '0000000000000000000000000000000000000000000000000000000000000000'
```
In the past this return would have passed the challenge
[Preview](https://saving-satoshi-git-fork-benalleng-issue547-savingsatoshi.vercel.app/en/chapters/chapter-2/scripting-2?dev=true)
=> Enhance validation script on scripting 2

ui/lesson/ScriptingChallenge/Editor.tsx
cleans up the dead space on the editor terminal now that some of the space has been more finalized
Current
This PR
notice the bottom of the terminal no longer has blank space
=> Adjust Scripting Challenge Editor height

content/lessons/chapter-5/derive-message-1.tsx, i18n/locales/en.ts
This PR closes #858  and  replaces `<br/>` tag with \n
=> Fixed the Key Prop warning on derive-message-1

ui/lesson/ScriptingChallenge/index.tsx
Fixes an error Jonas found whereby the code comment removal regex had some errors
Also fixes an error whereby the wrong default language was selected when loading in from an existing account without localStorage
=> fix python code comment regex

contexts/ProgressContext.tsx
This revert the change from #880 it did not behave how I wanted it to when logging in from blank localstorage i.e. new / fresh browsers
=> revert ProgressContext

components/Navbar/NavbarMobile/NavbarMobile.tsx
I noticed that the body doesn't scroll if a user leaves the navbar navigation with either the back button or the power button so I add an unMount function to remove the overflow hidden 
This is on mobile
=> Remove overflow hidden on body when navbar unmounts

i18n/locales/en.ts
In the chapter 6, Put it Together (https://savingsatoshi.com/en/chapters/chapter-6/put-it-together-1) challenge, there is a table for the elements that make up the transaction input digest (aka the thing you have to sign when you sign a transaction input). 
According to [BIP-143](https://github.com/bitcoin/bips/blob/master/bip-0143.mediawiki), the sequence number should be 4 bytes, not 8.
=> Chapter 6: fix number of bytes for sequence number

content/resources/chapter-6/put-it-together.tsx, i18n/locales/en.ts
For the last challenge in chapter 6, "Sign the transaction", the player needs to update the change amount so miner fees are accounted for. I know we've [already added a comment](https://github.com/saving-satoshi/saving-satoshi/pull/931/files#diff-ea94042999c5e65bd33509c7502b7ab2a3ed6f8e8c24f93d2db08b56886e59c4R195) in the pre-loaded code that reminds the player to do this, but I think it also makes sense to call this out in the solution page as well. 
Does the JS text editor/code display frame dislike comments in solutions?
Python looks good
=> Chapter 6: update solution for last challenge

content/resources/chapter-6/put-it-together.tsx, i18n/locales/en.ts
**Chapter 6, Putting it all together, Build the witness class**
One part of this exercise is implementing the following (last step for signing an input with your private key):
```
// Extra Bitcoin rule from BIP 146
// https://github.com/bitcoin/bips/blob/master/bip-0146.mediawiki#user-content-LOW_S
//   s = -s mod n, if s > n / 2
```
In the solutions page, it is implemented as:
~~However line 45 should be if (s > (secp256k1.ORDER / 2)) (as opposed to 2n). n is not defined in the code, and if you look through the rest of the solution, n actually represents the order of the curve, secp256k1.ORDER.~~
This is confusing because n represents the order of the curve, but it's also being used here to coerce a number into a BigInt.
This PR replaces `2n` with `BigInt(2)` so the "n" character isn't …
=> Chapter 6: Clarify "n" value in solution

README.md, public/manifest.json
Add notes to the README about linting and the Husky hook. Also update `public/manifest.json` with the changes made after running `yarn prettier`. The Husky hook is not configured to look at `.json` files so this never had `pretttier` run against it.  It changed the direction of the slash marks from back slashes to forward slashes. When I ran the changes locally and briefly clicked around, everything seemed okay.
=> README: add linting notes

i18n/locales/en.ts
On the chapter 2 help page we have a few bits of code mentioned in the Tips section. In this PR I update the formatting to better match the rest of the game.
Are there any React best practices that I should consider as we go forward? Is this the preferred way to apply this kind of styling? I plan to tackle some more help pages and will be likely be adding more content similar to this.
Before:
After PR:
=> Design: Update code examples on ch 2 help page

ui/common/CodeExample.tsx
In chapter 6 we have some [really nice tables](https://savingsatoshi.com/en/chapters/chapter-6/in-out-5) where the background color is an opaque black. I thought it might be nice to update code examples to match this. What do we think? Are there any other areas of the project (other than challenges in other chapters) that use this CodeExample element that I should check on?
Screenshot from production:
After this PR:
=> Design: Darken the CodeExample element

ui/lesson/ScriptingChallenge/LanguageTabs.tsx
This modifies the reset terminal tooltip to not be clickable anymore, I found that it caused some weird behavior before that may cause a user to accidentally click the reset button
Only the icon is clickable now
=> Terminal tooltip now not clickable

content/lessons/chapter-8/building-blocks-5.tsx, content/lessons/chapter-8/building-blocks-6.tsx, content/lessons/chapter-8/building-blocks-7.tsx, i18n/locales/en.ts
I just finished playing chapter 8 and this PR contains a bunch of updates I have for it. It's best to review this PR by looking at each commit in sequential order.
**Commit 1** - copy changes and a few style updates similar to previous PRs I've made:
**Commit 2** - [building-blocks-5] Fix hashes in the challenge instructions. Prior to this change, the instructions did not match what is in
the pre-loaded code, and what the validation code is looking for.
**Commit 3** - [building-blocks-5] Add a default return value to the preloaded code. The user eventually has to change this, but it at least fixes an exception that prevented the user from debugging with `console.log()` statements.
**Commit 4** - [building-blocks-6] Add another custom (JavaScript) error message, this time for an incorrect …
=> Chapter 8 Updates

content/lessons/chapter-5/verify-signature-2.tsx
Just noticed this bug on one of the chapter 5 challenge instructions: https://savingsatoshi.com/en/chapters/chapter-5/verify-signature-2
Fixed:
=> Chapter 5: fix copy bug

content/lessons/chapter-8/building-blocks-3.tsx, content/lessons/chapter-8/building-blocks-4.tsx, content/lessons/chapter-8/building-blocks-5.tsx, content/lessons/chapter-8/building-blocks-7.tsx, content/lessons/chapter-8/building-blocks-8.tsx, content/resources/chapter-8/building-blocks-3.tsx, content/resources/chapter-8/building-blocks-4.tsx, content/resources/chapter-8/building-blocks-5.tsx, content/resources/chapter-8/building-blocks-6.tsx, content/resources/chapter-8/building-blocks-7.tsx, i18n/locales/en.ts
This PR adds semicolons to a lot of the default JS starter code that comes with challenges. I know it technically doesn't matter, but adding them makes the code consistent with the other chapters.
I also fixed the success message issue I filed here, https://github.com/saving-satoshi/saving-satoshi/issues/991. Didn't do anything fancy, just changed `(get subsidy)` to `get_subsidy` because I saw other success messages use the python function name.
=> Chapter 8: add semicolons to default JS code, fix a success message

i18n/locales/en.ts
Updates the chapter names again after satsie pointed out I actually named a chapter one that already existed, I found the chapter names from the old-school figma https://www.figma.com/design/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=2044-24387&t=inB0w8iCZ7b8UDoW-0
=> fix: update chapter names attempt 2

content/lessons/chapter-4/address-3.tsx, i18n/locales/en.ts, ui/common/Table.tsx
Chapter 4, address-3: add human readable prefixes to a table, provide more detailed instructions to the user
Before:
After:
=> Chapter 4, address-3: add prefix table, provide more instructions to user

content/lessons/chapter-5/verify-signature-2.tsx, content/lessons/chapter-5/verify-signature-3.tsx, content/lessons/chapter-5/verify-signature-4.tsx, content/resources/chapter-5/verify-signature-2.tsx, content/resources/chapter-5/verify-signature-3.tsx, content/resources/chapter-5/verify-signature-4.tsx, content/resources/chapter-5/verify-signature-5.tsx, i18n/locales/en.ts
This PR is a bunch of misc updates to Chapter 5, section 3 (verify-signature-*). To test it, click around https://saving-satoshi-git-fork-satsie-ch-5-js-tip-savingsatoshi.vercel.app/en/chapters/chapter-5/verify-signature-2 through https://saving-satoshi-git-fork-satsie-ch-5-js-tip-savingsatoshi.vercel.app/en/chapters/chapter-5/verify-signature-5
**Here's what's changing:**
- Update a few of the text blocks to look more like the rest of the layout:
- verify-signature-2: add a JavaScript hint. I put this in because I know at some point we want to track if spoilers are viewed. In that scenario, I assume we'd want to provide as much help to the user as we can so that viewing the spoiler is a last resort.
I added this specific tip because I initially tried to make an array of bytes instead of …
=> Chapter 5, verify-signature-*: design and resource page updates

content/lessons/chapter-5/verify-signature-2.tsx, content/lessons/chapter-5/verify-signature-5.tsx, i18n/locales/en.ts
This is a small PR with various updates to chapters 4 and 5:
Misc style updates:
- Chapter 4 - public-key-3 tips page: remove redundant challenge name now that each challenge has a unique help page
- Chapter 5 - verify-signature-2, verify-signature-5:  don't display title as normal text
- Chapter 5 - derive-message-6: add missing link
- Chapter 5 - make highlighted function names a monospace font
Lesson content updates:
- Chapter 4 - public-key-4 help page: add JavaScript tip to convert hex string to buffer
- Chapter 5 - refer to block 9 and block 170 when possible
=> Chapters 4 & 5: misc lesson content and styling updates

content/lessons/chapter-5/verify-signature-2.tsx
in chapter-5/verify-signature-2 we don't need to import base64 in python since this challenge is just hashing not a string decoding.
=> chore: Removed unused python import

api/auth/login.ts, state/progressState.ts, utils/index.ts
There was a race condition when writing the session token on signup so occasionally the signup modal would fail to close.
=> fix: Fixed race condition for local storage write on signup

ui/lesson/OpRunner/OPFunctions.ts, ui/lesson/OpRunner/OpRunner.tsx
This makes all text inputs in the OPRunner upper case and fixes an error in `OP_EQUALVERIFY` not returning anything
=> Script case

content/lessons/chapter-4/public-key-2.tsx
Adapt the curve equation to match secp256k1: $y^2 = x^3 + 7$
Note that the curve $y^2 = x^2 + 7$ would look very different, see e.g. https://www.desmos.com/calculator/ for trying out.
=> fix: correct elliptic curve equation s/x^2/x^3/ in chapter 4

hooks/useEnvironment.ts
@benalleng Is this what you had in mind?  This would mean we would never be able to use dev mode in the production build.
=> chore: Protect dev mode in production

app/[lang]/chapters/[slug]/[lesson]/page.tsx, config/metadata/index.ts
Closes #918 
the duplicate meta tag is there as we can't set metadata on `use-client` components so I added it in with the `<Portal/>` component
=> Set maximum viewport scale

content/lessons/chapter-4/address-3.tsx
In Chapter 4,  Get a P2WPKH address, the default Python script recommends the user check a URL to see how to use the `encode` function from the `bech32`library. The link does not exist, however, but I could find the file with the `encode` function in another repository of _saving-satoshi_, with the same file name `bech32.py`, so I took the time to recommend this fix for future users that may be stuck on that part of this awesome adventure.
**Current:** https://github.com/saving-satoshi/challenges/blob/master/chapter4/python/lib/bech32.py
**Correct:** https://github.com/saving-satoshi/bech32py/blob/main/bech32py/bech32.py
=> fix: Ch4 - Get a P2WPKH address - Python  - Tip 404 URL for bech32.py

ui/lesson/OpCodeChallenge/OpRunner.tsx
Fixes a bug where opcodes weren't being highlighted on values !== `1` or `true`
=> Script Highlighting

i18n/locales/en.ts
Closes #1113 
This was a stale link to an old repo with all the answers :sweat_smile: 
@kaiosatiro You can view the new link [here](https://github.com/saving-satoshi/resources/blob/main/chapter-7/mempool.json) in the interim before it gets merged to master
=> fix: stale mempool links for chapter 7

ui/lesson/ScriptingChallenge/Runner/index.tsx
This will allow the terminal to display an error on a closed ws so the user knows that there is something wrong with the image and it no longer will hang
=> Display error on closed ws

ui/chapter/Chapter.tsx
Fixes a bug where the info and challenges tabs were using visibility classes instead of display css
Closes #1099 
[Preview](https://saving-satoshi-git-fork-benalleng-chapter-4c7b3f-savingsatoshi.vercel.app/en/chapters?dev=true)
=> Chapters page chapter tabs consistency

components/Hero.tsx, state/AuthFunctions.ts
Removes the `Tell me more` button and replaces start with continue when logged in on the Hero homepage
=> Add continue button on Hero homepage when logged in

content/lessons/chapter-4/address-3.tsx, hooks/useProceed.ts, state/FeatureFunctions.ts, ui/chapter/Chapter.tsx
An attempt to work on #1071 and #1124.  This doesn't immediate fix the issue whereby the progress object was being incorrectly set when transitioning to a different difficulty mode but it does fix what I believe is a follow-on problem whereby we still had some router.push when it should have been first progressing to the next lesson
=> Progress object consistency within hard-mode

ui/lesson/ScriptingChallenge/Runner/index.tsx
Now encodes the repl stream code to base64 to remove the `\n` and other whitespace in the `JSON.stringify()` pairs with https://github.com/saving-satoshi/saving-satoshi-backend/pull/54
=> Repl code base64 encoded

content/lessons/chapter-6/normal/in-out-4.tsx, i18n/locales/en.ts
In this PR I've fleshed out some of the instructions for chapter 6's in-out-four-normal challenge. I'd like to copy some of these updates over to the hard version of the challenge, but will do so as a separate PR.
Before:
After:
[Preview](https://saving-satoshi-git-fork-satsie-ch6-challen-611092-savingsatoshi.vercel.app/en/chapters/chapter-6/in-out-4-normal?dev=true)
=> ch6 in-out-four-normal: add more detail to instructions

ui/lesson/TransactionsChallenge/OutputScript.tsx
Fixes a regression in the textarea uppercase that formed because of the `scriptInput[objectOutput]` complexity
=> Fix textarea uppercase

content/lessons/chapter-6/hard/put-it-together-3.tsx, content/lessons/chapter-6/normal/put-it-together-1.tsx, content/resources/chapter-6/put-it-together-1-normal.tsx, content/resources/chapter-6/put-it-together-3-hard.tsx
This is a long needed change as `createHash` has been around for a while and `Hash` is ultimately an old method. This PR does not do anything to check node versions only to replace the `Hash` function with `createHash`.
> Need to do more investigation. The solution is to likely fix the answer code, and it might make sense to upgrade NodeJS on our repl containers. Not sure what version it's running right now.
We must uses latest or something, I can't remember
Closes #1261 
[Preview](https://saving-satoshi-git-fork-benalleng-deprecat-6017c5-savingsatoshi.vercel.app/en/chapters/chapter-6/in-out-5?dev=true)
=> Deprecate crypto.Hash function in favor of createHash
