- README.md
- Updating basic description
- Add local dev setup into
- Add basic contribution info
- Roadmap tweaks
-
-
-
> Revising the README to be more up-to-speed

- app/chapters/[slug]/layout.tsx
- app/chapters/[slug]/page.tsx
Can't create a validad next build
- Next build is generating a valid build
> Deleted unnecesary files, change exports

- app/chapters/[slug]/page.tsx
- app/chapters/page.tsx
- components/ChapterOverview.tsx
- components/Hero.tsx
- components/partials/Overview.tsx
Improved responsiveness of various pages and components.
Center image on mobile
Responsive 'Start Chapter' button & padding around page
Padding around chapter page
Partially addresses #11.
Didn't address the challenge page yet. I think it needs some more desktop work first?
> Various responsive improvements

- app/about/page.tsx
This PR adds the About Page.
The fonts used are incorrect but I don't think it is related to this PR.
Desktop
Mobile
Closes #5.
> Add about page

- components/Hero.tsx
The tag line on the hero banner is outdated because it mentions time travel.
- Update tagline to "Code your way through the mysteries of bitcoin". I haven't updated anything in Figma, and am happy to make changes to this PR/close it in favor of another one.
> Update tagline on hero

- app/about/page.tsx
About page is outdated. See issue #5
- Updated story
- Added additional contributors
- Added links to contributor profiles
resolves #5
> Update About page to reflect new storyline. Add links to contributors.

- README.md
The `npm run build` step was missing from local development instructions. As far as I could tell, I needed to run this command after each change, or updates would not be picked up during `npm run start`.
Also the the intro video is quite outdated now, at least as far as the story goes.
- Add `npm run build` step to the local instructions
- Remove the link to the old intro video. We can always create a new one.
- Make some updates to the project overview.
> Update README to add build step. Also refresh outdated project summary.

- app/about/page.tsx
- app/chapters/[slug]/genesis/genesis-pt2/page.tsx
- app/chapters/[slug]/genesis/page.tsx
- app/chapters/[slug]/page.tsx
- app/chapters/[slug]/transacting/layout.tsx
- app/chapters/[slug]/transacting/page.tsx
- app/chapters/[slug]/transacting/transacting-1/page.tsx
- app/chapters/[slug]/transacting/transacting-2/page.tsx
- app/page.tsx
- components/Fonts.tsx
- components/Footer.tsx
- components/Hero.tsx
- components/NavBar.tsx
- components/Terminal.tsx
- components/chapters/ChaptersNavbar.tsx
- components/chapters/partials/Tab.tsx
- components/chapters/partials/TabGroup.tsx
- components/partials/Challenges.tsx
- components/partials/ListItem.tsx
- components/partials/Overview.tsx
- components/partials/TabGroup.tsx
- styles/globals.css
Lots of little things on the home, about, chapter, and various content pages. Did not get through the last few content pages though.
> Lots of visual tweaks

- components/partials/Challenges.tsx
- components/partials/ListItem.tsx
- components/partials/TabGroup.tsx
A cleaner version of #34 without the junk commit history.
👻[Check the preview](https://saving-satoshi-git-feature-about-page-cha-003c28-saving-satoshi.vercel.app/chapters)👻
-
-
-
resolved #
> Made challenge links on the chapters page clickable V2

- app/chapters/[slug]/genesis/page.tsx
- app/chapters/[slug]/transacting/transacting-1/page.tsx
- components/Input.tsx
The console keeps complaining about these.
> Fixing a few CSS object propery names

- app/chapters/[slug]/genesis/genesis-pt2/page.tsx
- app/chapters/[slug]/transacting/transacting-2/page.tsx
- components/Terminal.tsx
- styles/globals.css
> Improve Terminal colors

- app/chapters/[slug]/genesis/genesis-pt2/page.tsx
- app/chapters/[slug]/transacting/transacting-2/page.tsx
- components/Terminal.tsx
- styles/globals.css
- Adds a first tip line to the Terminals in the two lessons that use it ("Enter your commands here and press Enter...")
- Tweaks colors and spacing of Terminal lines
- Changes ">" to always be in a pseudo-element to avoid glitches when submitting
[Check the preview](https://saving-satoshi-git-feature-terminal-color-tweaks-saving-satoshi.vercel.app/chapters/chapter-1/genesis/genesis-pt2)
> Minor color and spacing tweaks to the Terminal

- app/about/page.tsx
underline the links on about page, as requested in #82
> Underline links on about page

- content/introductions/reaping-rewards.mdx
- content/lessons/return-to-sender.mdx
A space is missing in text on chapter 1 and another page.
The spaces have been added.
This missing space is also present in copied text in WIP PR #80 
Screen showing missing space:
> Add missing spaces in text content

- app/chapters/[slug]/genesis/genesis-pt2/page.tsx
- app/chapters/[slug]/transacting/transacting-2/page.tsx
- components/chapters/LoginModal.tsx
- components/chapters/SignUpModal.tsx
- components/ui/BoxButton.tsx
- components/ui/CopyButton.tsx
- components/ui/CopyableCode.tsx
- content/lessons/genesis-pt2.mdx
- content/lessons/transacting-2.mdx
- public/assets/icons/copy.svg
- public/assets/icons/copy_active.svg
- styles/globals.css
> Create CopyButton and use it

- components/chapters/LoginModal.tsx
Fix for site crashing immediately after load
Resolves #94 
Site crashes shortly after load.
Site does not crash.
> Load default avatar for not logged in users

- .github/workflows/ADD_ISSUES_TO_PROJECT.yml
Updating to v4 as v3 is no longer available.
> Updating to v4

- app/chapters/[slug]/genesis/genesis-pt2/page.tsx
- components/Tip.tsx
- components/Tips.tsx
- public/assets/icons/carret-right.svg
Fixes #54.
Adds reusable `Tips` and `Tip` components.
> Add tips to Chapter 1 Challenge 1 PT2

- components/ui/NavBar.tsx
> Fix Navbar design

- ui/common/StatusBar.tsx
Should help push us to resolving mobile formatting issues further. The next button does not appear when completing code on mobile in the cli pages.
> Mobile formatting on CLI code pages

- components/Modals/Login.tsx
- components/Modals/SignUp.tsx
- components/Topbar.tsx
- hooks/index.ts
- hooks/use-status.ts
- hooks/useHasMounted.ts
- hooks/useUser.ts
- lib/content.ts
- lib/user.ts
- package.json
- ui/chapter/End.tsx
- ui/lesson/TerminalChallenge.tsx
- yarn.lock
resolves https://github.com/saving-satoshi/saving-satoshi/issues/114
I fixed the bug, but can whoever reviews this make sure the signup and login flows are correct? I'm not 100% sure if they are correct just by looking at the mockups.
I used `use-local-storage-state` to access values from localStorage in order to make sure components using localStorage values re-render whenever the values in localStorage changes.
~~A lot of the changes are just formatting that was done by Prettier. I prettified every file that I touched which is a strategy I've used on codebases that are not fully prettified. If anyone does not agree with this strategy and would prefer to review a smaller changeset without all the formatting changes, let me know and I can simplify the PR.~~
I also removed any unused …
> fix: user state management

- .vscode/settings.json
- ui/chapter/Chapter.tsx
- ui/chapter/Tab.tsx
Fixes #127 
Fixed the layout for chapter page for mobile view.
**ScreenShot**
> Chapter overview layout issue for mobile view

- components/Navbar/Navbar.tsx
- components/Navbar/Tab.tsx
- components/Navbar/TabGroup.tsx
- components/Navbar/UserButton.tsx
- components/Topbar.tsx
- Address the first part of issue #66
- This PR separates the login/signup button into its separate component and uses it in the Navbar.
- Addresses other minor changes to fix alignment, adds the right border to the last challenge button, and fixes the used tags to make them more coherent.
Screenshot:
|Master|PR|
|-------|---|
|![Screenshot 2023-02-07 at 7 20 19 PM](https://user-images.githubusercontent.com/85434418/217263284-f3e68008-3219-47bd-b8bc-40695946e099.png)|![Screenshot 2023-02-07 at 7 19 37 PM](https://user-images.githubusercontent.com/85434418/217263120-e425a3cd-a9e1-4fa0-9ab4-f43a1a5bf3bc.png)|
> Add the Login/Signup Button to the navbar.

- components/Navbar/Tab.tsx
fixes #141 
- This PR reintroduces the isLast variable to keep track of the last challenge and to fix the `Reference Error: Can't find variable: isLast"`
> Reintroduce the isLast variable

- .vscode/settings.json
- content/lessons/done/index.tsx
- content/lessons/done/translations.ts
- middleware.ts
- ui/chapter/End.tsx
> Fix for missing translation on Done page

- components/Topbar.tsx
Fixes #149
Adding `/en` to the link in `Topbar.tsx` leads to the home page.
> Fix for title leads to 404 page

- content/lessons/transacting/transacting-2/index.tsx
- content/lessons/transacting/transacting-3/index.tsx
- content/lessons/transacting/transacting-3/translations.ts
> Fix broken translations for Transacting challenge

- .vscode/settings.json
- components/Modals/Login.tsx
- components/Modals/SignUp.tsx
- shared/Button.tsx
- shared/CopyButton.tsx
resolves the first part of #147 and fixes #168
**Changes**
- Minor styling changes (spacing, text size)
**Screenshot**
Figma link - https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=1112%3A14225&t=p997ySICoKBBYtU3-0
> Styling fix for signed in model

- components/Navbar/Address.tsx
- components/translations.ts
> Fix copy in Navbar

- components/Navbar/Tab.tsx
> Fix active state for Navbar Tabs

- hooks/useUser.ts
- lib/user.ts
Fixes #170
Changed `user` to `SavingSatoshiUser` and `loggedIn` to `SavingSatoshiLoggedIn`.
> Namespace keys (localstorage)

- components/HorizontalScrollView.tsx
- components/Modals/SignUp.tsx
Fixes #192
- This will allow displaying a horizontal slider when the window size is smaller than 767px. And otherwise, show the children in 5 column grid style.
- Used the Slider component in Signup.tsx file.
**Screenshot:**
_Introduced dummy avatars to show the difference._
|Desktop|Mobile|
|---------|------|
|<img width="555" alt="Screenshot 2023-02-27 at 8 06 42 PM" src="https://user-images.githubusercontent.com/85434418/221595748-26f91347-3ca1-4033-af02-3b63770d3a1c.png">|<img width="490" alt="Screenshot 2023-02-27 at 8 06 42 PM" src="https://user-images.githubusercontent.com/85434418/221596013-8558196d-3a80-4310-93cc-9d0f349a3f97.jpeg">|
> Introduced new Slider component.

- components/Navbar/UserButton.tsx
In order to improve accessibility add an aria-label to the profile button.
> Add an aria-label to the profile button to improve accessibility.

- content/lessons/genesis/genesis-2/index.tsx
Closes https://github.com/saving-satoshi/saving-satoshi/issues/180
> Remove tip from challenge 1

- ui/lesson/Terminal.tsx
Fixes #226 
changes:
- Added text wrap to terminal input.
- fixed the spanning of terminal height to occupy the entire screen.
> Added text wrap to terminal Input

- components/Navbar/NavbarDesktop/Tab.tsx
- i18n/locales/en/translations.ts
- i18n/locales/nl/translations.ts
- lib/translate.tsx
- ui/common/Tooltip.tsx
> Improve a11y for tooltips

- hooks/useLang.ts
> Fix missing translations on Homepage for english locale

- i18n/README.md
Added readme with more detailed instructions. Closes https://github.com/saving-satoshi/saving-satoshi/issues/258
> Update translation readme

- components/Navbar/NavbarDesktop/NavbarDesktop.tsx
- components/Navbar/NavbarMobile/NavbarMobile.tsx
- hooks/index.ts
- hooks/useContentRoute.ts
in order to fix #206. I removed useRouter and replaced it with useContentRouter to improve content route management, and I altered the back button in the Navigation Component to link to the chapters page.
> Navigation back button go to chapters page

- content/chapters/chapter-1/index.tsx
- content/lessons/genesis/genesis-1/index.tsx
- content/lessons/genesis/genesis-2/index.tsx
- content/lessons/genesis/genesis-3/index.tsx
- content/lessons/index.tsx
- content/lessons/transacting/transacting-1/index.tsx
- i18n/locales/en/translations.ts
- i18n/locales/nl/translations.ts
- ui/chapter/Intro.tsx
> Add intro page for genesis challenge

- components/Navbar/NavbarMobile/NavbarMobile.tsx
> NavBar Link keeps styling in mobile

- i18n/locales/en.ts
Updated Vanderpool->Vanderpoole
> Spelling changes

- i18n/locales/en.ts
Changed abandoned warehouse -> address. At this point the player has no idea it's an abandoned warehouse.
> Updated outro 2 copy

- ui/lesson/Terminal.tsx
> Turn off autoCapitalize for Terminal Challenge

- i18n/locales/en.ts
> Update copy for Ch1. challenge 1 pt 2.

- ui/common/Input.tsx
Closes #299 
[Preview](https://saving-satoshi-git-fork-benalleng-issue299-saving-satoshi.vercel.app/en/chapters/chapter-1/genesis-2)
> Fix Enter key behavior on Input

- ui/lesson/TerminalChallenge.tsx
Closes #301 
[Preview](https://saving-satoshi-git-fork-benalleng-issue301-saving-satoshi.vercel.app/en/chapters/chapter-1/genesis-3)
> Accept Double and Single quotes in Terminal Challenge

- content/lessons/chapter-1/transacting-3.tsx
- i18n/locales/en.ts
Updates the commonError following the update to the logic to accept the scriptPubKeyBytes string
> Update commonError for Transacting-3

- app/[lang]/chapters/page.tsx
> Background colour fix for chapters page

- app/[lang]/about/page.tsx
- app/[lang]/chapters/[slug]/[lesson]/page.tsx
- components/Hero.tsx
- components/Navbar/NavbarDesktop/NavbarDesktop.tsx
- components/Navbar/NavbarDesktop/Tab.tsx
- components/Navbar/NavbarMobile/TabMobile.tsx
- components/Topbar.tsx
- config/site.ts
- content/lessons/chapter-1/genesis-1.tsx
- content/lessons/chapter-1/genesis-2.tsx
- content/lessons/chapter-1/genesis-3.tsx
- content/lessons/chapter-1/genesis-4.tsx
- content/lessons/chapter-1/intro-2.tsx
- content/lessons/chapter-1/outro-1.tsx
- content/lessons/chapter-1/transacting-1.tsx
- content/lessons/chapter-1/transacting-2.tsx
- content/lessons/chapter-1/transacting-3.tsx
- hooks/useLocalizedRoutes.ts
- hooks/usePathData.ts
- i18n/locales/en.ts
- ui/chapter/ChallengeListItem.tsx
- ui/chapter/Chapter.tsx
- ui/common/StatusBar.tsx
- ui/common/TextImageLayout.tsx
- ui/introduction/Introduction.tsx
> Locale persistence + minor bugfixes

- components/Navbar/LangSwitch.tsx
- i18n/README.md
Closes #326 Closes #328 Closes #152
Final PR to close out the update to our new translation system.
To preview Readme
1. press ' . ' on this page to open the web-editor
1. right click on the `/i18n/README.md` fle and press 'open preview' or with the file opened press `Ctrl+Shift+V`
> Translation help link and Readme update

- .vscode/settings.json
- content/lessons/chapter-1/transacting-2.tsx
- content/lessons/chapter-1/transacting-3.tsx
- i18n/locales/en.ts
> Update: OP_RETURN for Ch1.L2

- .vscode/settings.json
- components/Navbar/HelpLink.tsx
- components/Navbar/NavbarDesktop/NavbarDesktop.tsx
- components/Navbar/NavbarMobile/NavbarMobile.tsx
- components/Navbar/UserButton.tsx
- content/lessons/chapter-1/transacting-2.tsx
- content/lessons/chapter-1/transacting-3.tsx
- i18n/locales/en.ts
Closes #343
Also cleans up some NavBar item classes to be more consistent
> Feedback Link

- app/[lang]/chapters/[slug]/[lesson]/layout.tsx
fixes #369
**Screenshot:**
|Master|PR|
|-------|---|
|<img width="1132" alt="Screenshot 2023-04-12 at 7 13 02 PM" src="https://user-images.githubusercontent.com/85434418/231477600-0584ac37-89e7-4f41-9bcb-83552f3ce36d.png">|<img width="1132" alt="Screenshot 2023-04-12 at 7 13 28 PM" src="https://user-images.githubusercontent.com/85434418/231477581-e211fd49-8882-4e07-96ed-7588506f6a48.png">|
> Removed drop shadow, and blur background from layout.tsx

- ui/common/TextImageLayout.tsx
Closes #374
Simply swaps router.replace with router.push to track the history for the back button too work with
> Back button now has standard behavior on intro pages

- components/Navbar/HelpLink.tsx
- components/Navbar/NavbarDesktop/NavbarDesktop.tsx
- components/Navbar/NavbarMobile/NavbarMobile.tsx
> Need help background

- i18n/locales/es.ts
Removed markdown in certain areas because it was not being correctly converted into styling.
> Update ES About Page

- hooks/useLessonStatus.ts
- lib/progress.ts
> Introduced new isChallengeCompleted function

- hooks/useSaveAndProceed.ts
> Add routes to useSaveandProceed hook

- ui/lesson/ScriptingChallenge/Runner/Hasher.tsx
- ui/lesson/ScriptingChallenge/Runner/index.tsx
- ui/lesson/ScriptingChallenge/index.tsx
fixes: #339
[preview](https://saving-satoshi-git-fork-vinayaksh42-issue339-saving-satoshi.vercel.app/en/chapters/chapter-2/scripting-2?dev=true)
> Styling fix for initial state of scripting challenge

- api/index.ts
- api/local/getProgress.ts
- api/local/index.ts
- api/local/setProgress.ts
- app/[lang]/chapters/[slug]/[lesson]/page.tsx
- hooks/useSaveAndProceed.ts
- providers/ProgressProvider.tsx
- types/interfaces.ts
- ui/lesson/TerminalChallenge.tsx
- yarn.lock
Resolves #331
- Removes the mandatory signup screen.
- Introduce an option for loading/saving progress locally when the user has not created the account.
> Remove Mandatory signup screen + Introduced local storage when account is not created

- middleware.ts
- public/robots.txt
> Add robots.txt

- ui/lesson/TerminalChallenge.tsx
> sanitize irregular whitespace around |

- components/Layout.tsx
- components/Modals/Account.tsx
- components/Modals/Modal.tsx
- components/Modals/SignIn.tsx
- components/Modals/SignUp.tsx
- package.json
- yarn.lock
This PR closes #409, removed our dependency on `react-modal` in favor of a custom implementation that we can modify how we see fit and it plays better with Next.js.
> Fix modals

- app/[lang]/[...not-found]/page.tsx
- app/[lang]/about/page.tsx
- app/[lang]/chapters/[slug]/[lesson]/page.tsx
- app/[lang]/chapters/page.tsx
- app/[lang]/not-found.tsx
- app/layout.tsx
- app/page.tsx
- ui/common/Tooltip.tsx
This PR closes #228 and #410, unfortunately I had to include some oddities in this PR to satisfy the Next build.
> Meta tags and document.title

- content/lessons/chapter-2/hashing-2.tsx
- i18n/locales/en.ts
- ui/lesson/HashChallenge.tsx
Closes #427
Tooltip changes are being worked on in #407 
[Preview](https://saving-satoshi-git-fork-benalleng-issue427-savingsatoshi.vercel.app/en/chapters/chapter-2/intro-1?dev=true)
> General QA fixes

- api/local/getProgress.ts
- api/progress/getProgress.ts
- app/[lang]/chapters/[slug]/[lesson]/page.tsx
- components/Modals/SignUp.tsx
- providers/ProgressProvider.tsx
- types/interfaces.ts
> Allow localProgress to persist after user Signs up or Logs out

- components/Modals/Modal.tsx
resolves #440
https://github.com/saving-satoshi/saving-satoshi/assets/85434418/872dd08b-7aca-4ee6-9e22-379e075756d6
> Allow Signup Modal to be scrollable

- app/[lang]/about/page.tsx
- i18n/locales/en.ts
Closes #370 
We can wait on merging this until Tuesday 4/25.
> Update About Page for v1

- components/Disclaimer.tsx
- components/Navbar/HelpLink.tsx
- components/Navbar/Navbar.tsx
- components/Navbar/NavbarDesktop/NavbarDesktop.tsx
- components/Navbar/NavbarMobile/Menu.tsx
- components/Navbar/NavbarMobile/NavbarMobile.tsx
- components/Navbar/UserButton.tsx
- content/lessons/chapter-1/genesis-1.tsx
- content/lessons/chapter-1/outro-2.tsx
- content/lessons/chapter-1/transacting-1.tsx
- content/lessons/chapter-2/hashing-1.tsx
- content/lessons/chapter-2/hashing-3.tsx
- content/lessons/chapter-2/hashing-5.tsx
- content/lessons/chapter-2/outro-1.tsx
- content/lessons/chapter-2/scripting-1.tsx
- i18n/locales/en.ts
- styles/globals.css
- ui/chapter/Chapter.tsx
- ui/chapter/End.tsx
- ui/chapter/Intro.tsx
- ui/common/Input.tsx
- ui/lesson/ScriptingChallenge/index.tsx
This PR addresses the following issues from #431
1. Chapter page styling to fix url fragment scroll behavior
2. InputChallenge responsize styling
3. outro page scroll behavior on mobile
4. navbar unecessary scrolling
5. Intro page consistent padding
6. Scripting challenge scroll fixes for mobile
> QA UX fixes

- i18n/locales/en.ts
Added missing " and also made copy in outro make more sense.
> Updated copy in Ch. 2

- lib/formatHash.tsx
- styles/globals.css
- ui/common/Hasher.tsx
- ui/common/MiningStatisticsNonce.tsx
Closes #458 
[hashing preview](https://saving-satoshi-git-fork-benalleng-issue458-savingsatoshi.vercel.app/en/chapters/chapter-2/hashing-2?dev=true)
[mining preview](https://saving-satoshi-git-fork-benalleng-issue458-savingsatoshi.vercel.app/en/chapters/chapter-2/mining-1?dev=true)
> formatHash colors properly

- content/lessons/chapter-2/mining-1.tsx
> Fix: Ch.2 Mining Block NumberFormat

- app/[lang]/chapters/[slug]/[lesson]/page.tsx
- ui/common/TextImageLayout.tsx
> Fix: scroll to top for Chapter.2 Intro-1

- components/Navbar/NavbarDesktop/Tab.tsx
- components/Navbar/NavbarMobile/TabMobile.tsx
- ui/chapter/ChallengeList.tsx
- ui/chapter/ChallengeListItem.tsx
- ui/chapter/Chapter.tsx
> Lock icon size for safari browser

- components/Hero.tsx
- components/Navbar/NavbarDesktop/NavbarDesktop.tsx
- components/Navbar/NavbarMobile/NavbarMobile.tsx
- hooks/useSaveAndReturn.ts
- lib/progress.ts
This will auto scroll from the start page if the user is already logged in and completed the first challenge taking them directly to their latest progress.
> Add fragment url from start page when the user has completed the first chapter

- i18n/locales/en.ts
- ui/chapter/End.tsx
Closes #487
Feedback link now a button and is only present on the final outro screen tracking the key array
> Feedback button for end screen

- content/lessons/chapter-2/mining-1.tsx
- ui/common/MiningStatisticsHash.tsx
- ui/common/MiningStatisticsNonce.tsx
Fixes: #488 
The user will now be able to find 1 block per 15 second (the same rate used in part-1 of the challenge). The 'transactions confirmed' as well as 'bitcoin earned' is updated along with 'Blocks found'.
preview: https://saving-satoshi-git-fork-vinayaksh42-issue488-savingsatoshi.vercel.app/en/chapters/chapter-2/mining-1?dev=true
> Ch2 - Mining: Part 2 of mining challenge more realistic

- content/lessons/chapter-2/mining-1.tsx
- styles/globals.css
- tailwind.config.js
- ui/common/MiningStatistic.tsx
- ui/common/MiningStatisticsHash.tsx
- ui/common/MiningStatisticsNonce.tsx
- utils/index.ts
fixes: #454
- Text fades in and fades out upon change.
- The highlight towards the end of the challenge ('tell me more' part) has a pulse effect in order to draw the attention of the user.
preview: https://saving-satoshi-git-fork-vinayaksh42-issue454-savingsatoshi.vercel.app/en/chapters/chapter-2/mining-1?dev=true
> Ch2 - Mining: Text and highlight border UX improvement

- i18n/locales/en.ts
The description in the chapters overview page needed to be updated as it didn't set the scene properly for Ch.2 due to our new narrative changes.
I also updated copy inside Ch.2Challenge2 due to recent comments and preparation for Ch.3. You can see the updated [copy here](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?type=design&node-id=4333%3A54392&t=JT0qrStY5AQPqHpC-1) in figma.
> Update ch.2 copy

- components/Navbar/Address.tsx
- components/Navbar/NavbarDesktop/NavbarDesktop.tsx
- components/Navbar/index.ts
Fix the address component on Navbar.
**Screenshot:**
|Master|PR|
|-------|---|
|![Screenshot 2023-06-13 at 7 35 06 PM](https://github.com/saving-satoshi/saving-satoshi/assets/85434418/51c2e2a1-443f-4929-9eb8-af7b594973fc)|![Screenshot 2023-06-13 at 7 34 51 PM](https://github.com/saving-satoshi/saving-satoshi/assets/85434418/b36967c1-43df-4d70-9d34-9989c8fc5128)|
> Fix Address component on Navbar

- content/lessons/chapter-2/mining-1.tsx
Release notes:
1. Fix for a stalling bug in the mining challenge https://github.com/saving-satoshi/saving-satoshi/pull/514
> Release 1.0.1

- components/Avatar.tsx
- components/HorizontalScrollView.tsx
- components/Modals/Modal.tsx
- components/Modals/SignUp.tsx
Closes #528, Closes #525
This also fixes some stray sizing errors, should now look like the original selector while behaving with the new logic
> Add onClick() to avatar button for accessibility

- components/Navbar/Address.tsx
> Navbar text overflow

- app/[lang]/chapters/[slug]/[lesson]/page.tsx
- app/layout.tsx
- content/lessons/chapter-2/scripting-2.tsx
- i18n/locales/en.ts
- styles/globals.css
- ui/lesson/ScriptingChallenge/Runner/Terminal.tsx
- ui/lesson/ScriptingChallenge/Runner/index.tsx
> Improve scripting challenge UX #513

- components/Navbar/Address.tsx
Fix #543
[preview](https://saving-satoshi-git-fork-vinayaksh42-issue543-savingsatoshi.vercel.app/en/chapters/chapter-1/genesis-1?dev=true)
> Navbar chapter and challenge overflow

- README.md
- license
> Add MIT license

- i18n/locales/en.ts
- ui/chapter/ChallengeList.tsx
- ui/chapter/Chapter.tsx
Restores the coming soon copy that went missing at some point. now visible on chapters with no content
> Coming soon copy on Chapters page

- app/.well-known/nostr.json
- middleware.ts
- public/.well-known/nostr.json
Should allow for savingsatoshi to have its own nip-05
> Ndd nostr nip-05 json

- content/chapters/chapter-3/index.tsx
- lib/progress.ts
Fixes the challenge order for chapter 3
Resolves #572
> change challenge order

- content/lessons/chapter-2/scripting-2.tsx
- package.json
- types/interfaces.ts
- ui/lesson/ScriptingChallenge/Editor.tsx
- ui/lesson/ScriptingChallenge/index.tsx
- yarn.lock
Resolves #577, made it so that we can set constraints on a per-lesson basis (see scripting-2.tsx).
> Constrained monaco editor

- components/Navbar/NavbarMobile/Menu.tsx
- content/chapters/chapter-3/index.tsx
- content/lessons/chapter-1/outro-2.tsx
- content/lessons/chapter-2/outro-1.tsx
- content/lessons/chapter-3/outro-1.tsx
- ui/chapter/DesktopEnd.tsx
- ui/chapter/End.tsx
- ui/chapter/MobileEnd.tsx
Should match the outro screens to this [figma](https://www.figma.com/file/0Fg2IiEbLI5o8juawKqkJM/Saving-Satoshi-images?type=design&node-id=679-6452&mode=design&t=dkD9QAef5GTT0LGP-0)
[Preview-1](https://saving-satoshi-git-fork-benalleng-mobileend-savingsatoshi.vercel.app/en/chapters/chapter-1/outro-2?dev=true)
[Preview-2](https://saving-satoshi-git-fork-benalleng-mobileend-savingsatoshi.vercel.app/en/chapters/chapter-2/outro-1?dev=true)
[Preview-3](https://saving-satoshi-git-fork-benalleng-mobileend-savingsatoshi.vercel.app/en/chapters/chapter-3/outro-1?dev=true)
> MobileEnd fix

- content/chapters/chapter-3/index.tsx
- content/lessons/chapter-3/coop-1.tsx
- content/lessons/chapter-3/coop-2.tsx
- content/lessons/chapter-3/index.ts
- content/lessons/chapter-3/outro-1.tsx
- content/lessons/chapter-3/pool-1.tsx
- content/lessons/chapter-3/pool-2.tsx
- content/lessons/chapter-3/pool-3.tsx
- content/lessons/chapter-3/solo-1.tsx
- i18n/locales/en.ts
- lib/progress.ts
- lib/themeSelector.ts
- ui/common/ContributionBar.tsx
- ui/lesson/HashrateChallenge.tsx
Closes #506 
[Preview](https://saving-satoshi-git-fork-benalleng-issue506-savingsatoshi.vercel.app/en/chapters/chapter-3/pool-1?dev=true)
- get the correct avatar images imported
> Chapter 3 Challenge 3 (Pool-Win)

- api/features/getFeatures.ts
- api/features/index.ts
- app/layout.tsx
- providers/FeatureProvider.tsx
- providers/index.ts
- types/interfaces.ts
- ui/chapter/Chapter.tsx
Closes #564
https://github.com/saving-satoshi/saving-satoshi-backend/pull/22 should be merged before this PR
> Feature flag system

- content/lessons/chapter-2/mining-1.tsx
- content/lessons/chapter-3/pool-1.tsx
- ui/common/StartButton.tsx
- ui/lesson/HashrateChallenge.tsx
This PR slows down the hashRateChallenge slightly and fixes some key prop errors in chapter 3
[Preview](https://saving-satoshi-git-fork-benalleng-hashchal-4f1c73-savingsatoshi.vercel.app/en/chapters/chapter-3/solo-1?dev=true)
> Slow hashrateChallenge and fix unique key errors

- i18n/locales/en.ts
Updated some grammar and language in ch. 1 lesson copy based on user interview feedback of a bitcoin expert.
> Update ch. 1 copy

- content/lessons/chapter-2/scripting-2.tsx
- i18n/locales/en.ts
closes https://github.com/saving-satoshi/saving-satoshi/issues/597
Well, at least the first two bullet points. I can't recall what this refers to:
> Should we also provide the function code inside the terminal like Kevin showed us on the call today?
> fix: update chapter 2 challenge 2 copy in English

- content/lessons/chapter-3/coop-2.tsx
- content/lessons/chapter-3/pool-3.tsx
- content/lessons/chapter-3/solo-1.tsx
- ui/common/ContributionBar.tsx
- ui/lesson/HashrateChallenge.tsx
- yarn.lock
Resolves #581, set the blocks found amount to 0 for 3 co-op players, set the Player to be the one to find blocks.
> Change blocks found amount found for coop-2, made player the on to find blocks

- content/lessons/chapter-3/coop-2.tsx
- content/lessons/chapter-3/pool-3.tsx
- styles/globals.css
- ui/common/Profile.tsx
- ui/common/ProfilesContainer.tsx
This PR should solve the issue of scrolling on 1290px screens and above, i had to reduce the gap and size of the containers on certain breakpoints  #590
> Fix width of miners displayed in Ch. 3 Challenge 2 and 3.

- i18n/locales/en.ts
Went through and tidied up the story including fixed some grammatical mistakes.
> Updated Ch. 3 Copy

- content/lessons/chapter-3/coop-1.tsx
This Pr references #587  and solves  on the styling  of chapter 3 challenge 2.
> Fix: max- width instead of width and fade in and out on waiting text and images

- ui/lesson/HashrateChallenge.tsx
> Add fade-in delay so all elements arrive together

- components/Fonts.tsx
Closes #631 
adds the 600 font weight to nunito font
> Add semibold font weight to nunito font

- content/lessons/chapter-1/intro-1.tsx
- content/lessons/chapter-1/intro-2.tsx
- content/lessons/chapter-2/intro-2.tsx
- content/lessons/chapter-3/intro-1.tsx
- content/lessons/chapter-3/solo-1.tsx
Closes #618
[Chapter 1](https://saving-satoshi-git-fork-benalleng-issue618-savingsatoshi.vercel.app/en/chapters/chapter-1/intro-1?dev=true)
[Chapter 2](https://saving-satoshi-git-fork-benalleng-issue618-savingsatoshi.vercel.app/en/chapters/chapter-2/intro-1?dev=true)
[Chapter 3](https://saving-satoshi-git-fork-benalleng-issue618-savingsatoshi.vercel.app/en/chapters/chapter-3/intro-1?dev=true)
> Add object-position to all Intros

- content/lessons/chapter-2/mining-1.tsx
- i18n/locales/en.ts
Closes #596 
[Preview](https://saving-satoshi-git-fork-benalleng-issue596-savingsatoshi.vercel.app/en/chapters/chapter-2/mining-1?dev=true)
> Add tenXHint copy

- ui/chapter/Intro.tsx
Closes #620 
[Preview](https://saving-satoshi-git-fork-benalleng-issue620-savingsatoshi.vercel.app/en/chapters/chapter-1/genesis-1)
> Use max-screen-width for ChapterIntro

- content/lessons/chapter-3/coop-2.tsx
- content/lessons/chapter-3/pool-3.tsx
- content/lessons/chapter-3/solo-1.tsx
- content/lessons/chapter-3/split-2.tsx
- ui/common/Profile.tsx
This PR closes #635,
Fix overflow on chapter 3 challenge 4 and remove unused flex and flex-col on paragraph.
> Fix: Increased Max-width on chapter 3 challenge 4, also removed unused flex , flex-col

- content/chapters/chapter-3/index.tsx
- content/lessons/chapter-3/coop-1.tsx
- content/lessons/chapter-3/coop-2.tsx
- content/lessons/chapter-3/coop-3.tsx
- content/lessons/chapter-3/index.ts
- content/lessons/chapter-3/pool-1.tsx
- content/lessons/chapter-3/pool-2.tsx
- content/lessons/chapter-3/split-2.tsx
- hooks/useSaveAndProceed.ts
- i18n/locales/en.ts
- lib/progress.ts
This PR closes #619 
I did  have to change the file names and also touch the routing of the new files
> Fix: Challenge 2 and 3 copy and file name changes

- content/lessons/chapter-3/split-2.tsx
- ui/common/ProfilesContainer.tsx
- ui/lesson/HashrateChallenge.tsx
This PR Closes #660 
Added a max-width only on challenge 4 so it does not affect other profile containers in other chapters
> fix: max-width and reduce padding

- ui/common/ContributionBar.tsx
This PR closes #632 .
@afterburn , this might need an extra check because i did touch the contributions bar component.
Although everything looks fine from my end.
> fix: avatar cutting off on contribution bar

- content/lessons/chapter-4/public-key-1.tsx
- content/lessons/chapter-4/public-key-2.tsx
- content/lessons/chapter-4/public-key-3.tsx
- content/lessons/chapter-4/public-key-4.tsx
- content/lessons/chapter-4/public-key-5.tsx
- lib/progress.ts
> fix: issue with crashing when progress is in cha4

- content/lessons/chapter-3/coop-1.tsx
- content/lessons/chapter-3/pool-1.tsx
- i18n/locales/en.ts
I noticed the player avatar in 2 pool screens were the generic `avatars/1.png`. Only in the follow up screens they were updated to the actual avatar.
> Fix avatars and typos

- components/Avatar.tsx
- content/lessons/chapter-3/coop-1.tsx
- content/lessons/chapter-3/coop-3.tsx
- content/lessons/chapter-3/pool-1.tsx
- content/lessons/chapter-3/pool-2.tsx
- content/lessons/chapter-3/solo-1.tsx
- content/lessons/chapter-3/split-2.tsx
- ui/common/Profile.tsx
> Increase avatar image quality and size

- README.md
- i18n/README.md
- i18n/locales/en.ts
- i18n/locales/es.ts
- i18n/locales/hi.ts
- i18n/locales/nl.ts
Just minor copy updates:
- We're on Discord these days
- Minor update to the image generation info
- Minor typo fixes
> Change Slack to Discord

- types/interfaces.ts
- ui/lesson/ScriptingChallenge/Editor.tsx
- ui/lesson/ScriptingChallenge/config.ts
- ui/lesson/ScriptingChallenge/index.tsx
Adds a lineNumber function to allow for all hidden code to disappear in the IDE
> Adjustable lineNumbers and hiddenArea

- ui/lesson/ScriptingChallenge/Runner/index.tsx
Closes #690 and allows variant successMessage
[Preview](https://saving-satoshi-git-fork-benalleng-issue690-savingsatoshi.vercel.app/en/chapters/chapter-4/public-key-3?dev=true)
> Fix runner display

- ui/lesson/ScriptingChallenge/index.tsx
adds saveData for scripting challenges
> Save data for ScriptingChallenge

- app/page.tsx
- components/Util/Tracking.tsx
- styles/globals.css
Added Umami tracking.  Completes issue #699 
> chore: Added umami tracking

- content/lessons/chapter-4/public-key-3.tsx
- content/lessons/chapter-4/public-key-4.tsx
- types/interfaces.ts
- ui/lesson/ScriptingChallenge/index.tsx
> PublicKey 4 challenge (Challenge 2)

- ui/lesson/ScriptingChallenge/Runner/Terminal.tsx
- Removed css for error/success
- Made all terminal output white with 0.75 opacity
Fixes #558 
> chore: Improved terminal colours

- content/lessons/chapter-3/intro-1.tsx
- content/lessons/chapter-4/intro-1.tsx
Fixes image position on Chapter-3 and Chapter-4 intro
[Chapter 3](https://saving-satoshi-git-fork-benalleng-intro-image-savingsatoshi.vercel.app/en/chapters/chapter-3/intro-1?dev=true)
[Chapter 4](https://saving-satoshi-git-fork-benalleng-intro-image-savingsatoshi.vercel.app/en/chapters/chapter-4/intro-1?dev=true)
> Image positions on chapter 3 and chapter 4 intros

- app/[lang]/about/page.tsx
- i18n/locales/en.ts
> feat: Added privacy statement

- next-env.d.ts
Our next-env file has a new comment change, wanted to add this to make sure not everyone has this as a permanent diff on local
> Next-env change

- content/lessons/chapter-5/derive-message-1.tsx
- content/lessons/chapter-5/derive-message-6.tsx
- i18n/locales/en.ts
- types/index.ts
- ui/common/Input.tsx
- ui/lesson/Info.tsx
- ui/lesson/InputChallenge.tsx
- ui/lesson/Prompt.tsx
Still fixing some visual quirks but raising as a draft for now so you can provide any feedback.
> feat: Added chapter 5 challenge 1 part 2

- content/lessons/chapter-4/public-key-3.tsx
- content/resources/chapter-4/public-key.tsx
Closes #728 
Also removes unhelpful copy of `#import ECDSA` as this has been done already and hidden
ATM can't reproduce the primary issue
> Test solution IDE size

- i18n/locales/en.ts
> fix: Fixed typo in chapter 4

- .env.example
> chore: Added ws endpoint to example env file

- content/lessons/chapter-5/verify-signature-5.tsx
- content/resources/chapter-4/public-key.tsx
- content/resources/chapter-5/index.ts
- content/resources/chapter-5/verify-signature.tsx
- content/resources/index.tsx
- i18n/locales/en.ts
> feat: Added chapter 5 challenge 2 part 5

- i18n/locales/en.ts
- ui/lesson/ScriptingChallenge/Editor.tsx
> Editor opacity and typos

- content/lessons/chapter-5/validate-signature-2.tsx
- content/lessons/chapter-5/verify-signature-1.tsx
- i18n/locales/en.ts
Closes #719 
[Preview](https://saving-satoshi-git-fork-benalleng-issue719-savingsatoshi.vercel.app/en/chapters/chapter-5/validate-signature-2?dev=true)
> Chapter 5 Validate Signature 2

- content/lessons/chapter-5/verify-signature-2.tsx
- content/lessons/chapter-5/verify-signature-5.tsx
- content/resources/chapter-5/verify-signature.tsx
- i18n/locales/en.ts
- ui/lesson/ScriptingChallenge/Runner/index.tsx
- Changes to runner to support console logs during runtime
- Added verify signature 2
- verify signature 5 now supports console logs during runtime
> feat: Chapter 5 challenge 1 part 4

- content/lessons/chapter-5/validate-signature-1.tsx
- i18n/locales/en.ts
> Chapter 5 challenge 3 scripting challenge

- content/resources/chapter-2/scripting.tsx
- content/resources/chapter-4/address.tsx
- content/resources/chapter-4/public-key.tsx
- content/resources/chapter-5/derive-message.tsx
- content/resources/chapter-5/index.ts
- content/resources/chapter-5/validate-signature.tsx
- content/resources/chapter-5/verify-signature.tsx
- i18n/locales/en.ts
Closes #742 
[derive-message-preview](https://saving-satoshi-git-fork-benalleng-chapter-d81fe0-savingsatoshi.vercel.app/en/chapters/chapter-5/derive-message-1/help)
[validate-signature-preview](https://saving-satoshi-git-fork-benalleng-chapter-d81fe0-savingsatoshi.vercel.app/en/chapters/chapter-5/validate-signature-1/help)
> Remaining chapter 5 help pages

- content/lessons/chapter-5/validate-signature-3.tsx
- i18n/locales/en.ts
- ui/lesson/ScriptingChallenge/library/secp256k1py.ts
[Preview link](https://saving-satoshi-git-fork-daviroo-validate-s-43a2cc-savingsatoshi.vercel.app/en/chapters/chapter-5/validate-signature-3?dev=true)
> feat: Added validate signature 3

- app/sitemap.ts
- middleware.ts
- public/robots.txt
This PR closes #230  
although we are not adding all chapters because they are protected and dependent on the progress which the users progress which the web crawlers will 99% know nothing about.
> Generated sitemap dynamically and render

- content/lessons/chapter-5/derive-message-7.tsx
- i18n/locales/en.ts
Closes #714
[Preview](https://saving-satoshi-git-fork-benalleng-transact-e9e210-savingsatoshi.vercel.app/en/chapters/chapter-5/derive-message-7?dev=true)
> Chapter 5 Derive Message 7

- content/lessons/chapter-5/validate-signature-4.tsx
- i18n/locales/en.ts
- ui/lesson/ScriptingChallenge/library/secp256k1py.ts
> feat: Added validate signature 4

- ui/lesson/ScriptingChallenge/Runner/Terminal.tsx
makes a small addition to the terminal stlyes so they are reset on each input
> Reset Terminal style between inputs

- ui/common/StartButton.tsx
This PR closes #741 by adding flex-wrap-reverse
> fix: added flex-wrap-reverse on mining challenge

- content/chapters/chapter-6/index.tsx
- content/lessons/chapter-5/derive-message-1.tsx
- content/lessons/chapter-6/in-out-1.tsx
- content/lessons/chapter-6/in-out-2.tsx
- content/lessons/chapter-6/in-out-3.tsx
- content/lessons/chapter-6/in-out-4.tsx
- content/lessons/chapter-6/in-out-5.tsx
- content/lessons/chapter-6/index.ts
- content/lessons/chapter-6/intro-1.tsx
- content/lessons/chapter-6/intro-2.tsx
- content/lessons/chapter-6/outro-1.tsx
- content/lessons/chapter-6/put-it-together-1.tsx
- content/lessons/chapter-6/put-it-together-2.tsx
- content/lessons/chapter-6/put-it-together-3.tsx
- content/lessons/chapter-6/put-it-together-4.tsx
- content/lessons/chapter-6/put-it-together-5.tsx
- content/lessons/chapter-6/put-it-together-6.tsx
- content/lessons/index.tsx
- i18n/locales/en.ts
- lib/progress.ts
Closes #764 
adds files and progress object for chapter 6
[Preview](https://saving-satoshi-git-fork-benalleng-chapter-4187bd-savingsatoshi.vercel.app/en/chapters?dev=true#chapter-6)
> File structure scaffold for chapter 6

- content/lessons/chapter-4/address-2.tsx
- content/lessons/chapter-4/address-3.tsx
- content/lessons/chapter-4/public-key-4.tsx
- content/lessons/chapter-5/verify-signature-2.tsx
- content/resources/chapter-4/address.tsx
- content/resources/chapter-4/public-key.tsx
- i18n/locales/en.ts
Looks like we diverged from the challenge repo made a change to see if this is right for address 2
also fixes some copy
[Preview](https://saving-satoshi-git-fork-benalleng-challeng-ac8ca6-savingsatoshi.vercel.app/en/chapters/chapter-4/address-2?dev=true)
> Chapter 4/5 update #2

- api/data/getData.ts
- api/data/setData.ts
- content/lessons/chapter-4/address-1.tsx
- content/lessons/chapter-4/address-2.tsx
- content/lessons/chapter-4/address-3.tsx
- content/lessons/chapter-4/public-key-4.tsx
- providers/DataProvider.tsx
- types/classes.ts
- types/index.ts
- ui/lesson/ScriptingChallenge/Runner/index.tsx
- ui/lesson/ScriptingChallenge/index.tsx
Raising as a draft for now so you can get eyes on it early.  I haven't tested it yet but just to get feedback on the general approach.
> feat: Add store code in backend

- content/lessons/chapter-6/in-out-1.tsx
- i18n/locales/en.ts
- styles/globals.css
- ui/lesson/ScriptingChallenge/Editor.tsx
- ui/lesson/ScriptingChallenge/PlainEditor.tsx
- ui/lesson/ScriptingChallenge/PlainEditorWrapper.tsx
This PR closes #766 and creates a new component for a read only editor without languages tab
> Read-only editor for bitcoin script

- content/lessons/chapter-6/outro-1.tsx
- i18n/locales/en.ts
Closes #769 
[Preview](https://saving-satoshi-git-fork-benalleng-issue769-savingsatoshi.vercel.app/en/chapters/chapter-6/outro-1?dev=true)
> Chapter-6 outro

- i18n/config.ts
- i18n/locales/de.ts
- i18n/locales/index.ts
See Issue https://github.com/saving-satoshi/saving-satoshi/issues/808#issue-2066234969
Translated up to and including chapter 5.  Happy to keep going as soon as additional chapters are available.
> Adding german as a language option

- content/lessons/chapter-6/intro-1.tsx
- jest.config.js
- lib/SavedCode.test.ts
- lib/SavedCode.ts
- package.json
- yarn.lock
We need this as shared code for challenges which are saving/loading code so contributing it as a separate PR.
> chore: Added function to organize imports in saved code

- content/lessons/chapter-6/put-it-together-2.tsx
- content/lessons/chapter-6/put-it-together-3.tsx
- i18n/locales/en.ts
- ui/lesson/ScriptingChallenge/index.tsx
> Chapter 6 Challenge 2 Transaction Digest

- content/lessons/chapter-6/in-out-1.tsx
- content/lessons/chapter-6/in-out-4.tsx
- content/lessons/chapter-6/in-out-5.tsx
- i18n/locales/en.ts
Closes #767 
Validation works on both JS and Python
also made a change where there were some misordered challenges `in-out-4` <=> `in-out-5`
also added a continue button in `in-out-1` where there was none
[Preview](https://saving-satoshi-git-fork-benalleng-issue767-savingsatoshi.vercel.app/en/chapters/chapter-6/in-out-4?dev=true)
> Input class

- content/lessons/chapter-6/in-out-5.tsx
- content/lessons/chapter-6/put-it-together-1.tsx
- content/lessons/chapter-6/put-it-together-2.tsx
- content/lessons/chapter-6/put-it-together-3.tsx
- content/lessons/chapter-6/put-it-together-4.tsx
- content/lessons/chapter-6/put-it-together-5.tsx
- content/lessons/chapter-6/put-it-together-6.tsx
- ui/lesson/ScriptingChallenge/LanguageTabs.tsx
- ui/lesson/ScriptingChallenge/index.tsx
This PR closes issue #786, 
also added a prop (languageLocked) to make unused language hidden on the scripting challenge
> Added REPL language locked, detect language on editor load

- content/lessons/chapter-6/in-out-5.tsx
- content/resources/chapter-6/in-out.tsx
- content/resources/chapter-6/index.ts
- content/resources/chapter-6/put-it-together.tsx
- content/resources/index.tsx
- i18n/locales/en.ts
Closes #779 
Haven't added full copy in the resources yet, I think I will need some help from the group on this as well as possibly some user feeback on what is confusing
[in-out Preview](https://saving-satoshi-git-fork-benalleng-issue779-savingsatoshi.vercel.app/en/chapters/chapter-6/in-out-4/help)
[put-it-together Preview](https://saving-satoshi-git-fork-benalleng-issue779-savingsatoshi.vercel.app/en/chapters/chapter-6/put-it-together-4/help)
> Chapter 6 Help Pages

- content/lessons/chapter-6/in-out-5.tsx
- content/lessons/chapter-6/put-it-together-1.tsx
- content/lessons/chapter-6/put-it-together-2.tsx
- content/lessons/chapter-6/put-it-together-4.tsx
- content/lessons/chapter-6/put-it-together-5.tsx
- content/lessons/chapter-6/put-it-together-6.tsx
- content/resources/chapter-6/put-it-together.tsx
- i18n/locales/en.ts
- ui/lesson/ScriptingChallenge/index.tsx
rebase error from #823 
return code indentation back to normal
> Indentation bug

- content/lessons/chapter-6/in-out-4.tsx
- content/lessons/chapter-6/in-out-5.tsx
- content/lessons/chapter-6/put-it-together-1.tsx
- content/lessons/chapter-6/put-it-together-2.tsx
- content/lessons/chapter-6/put-it-together-3.tsx
- content/lessons/chapter-6/put-it-together-4.tsx
- content/lessons/chapter-6/put-it-together-5.tsx
- content/lessons/chapter-6/put-it-together-6.tsx
- i18n/locales/en.ts
Addresses feedback from @pinheadmz to prevent some user error on variable overlap and fixes copy changes
> Chapter 6 QA fixes

- content/chapters/chapter-7/index.tsx
- content/lessons/chapter-7/index.tsx
- content/lessons/chapter-7/intro-1.tsx
- content/lessons/chapter-7/intro-2.tsx
- content/lessons/chapter-7/intro-3.tsx
- content/lessons/chapter-7/mempool-transaction-1.tsx
- content/lessons/chapter-7/outro-1.tsx
- content/lessons/index.tsx
- i18n/locales/en.ts
- lib/progress.ts
Closes  #826 
Addition to the progress object as below
The challenge name is mempool-transaction-1
Progess array
`
'CH7INT1',
'CH7INT2',
'CH7INT3',
'CH7MPT1',
'CH7OUT1',
`
` CH7INT1: { path: '/chapter-7/intro-1' },
CH7INT2: { path: '/chapter-7/intro-2' },
CH7INT3: { path: '/chapter-7/intro-3' },
CH7MPT1: { path: '/chapter-7/mempool-transaction-1' },
CH7OUT1: { path: '/chapter-7/outro-1' },`
> Scafold chapter 7 for implementation

- content/lessons/chapter-6/in-out-4.tsx
- content/lessons/chapter-6/in-out-5.tsx
- content/lessons/chapter-6/put-it-together-1.tsx
- content/lessons/chapter-6/put-it-together-3.tsx
- content/lessons/chapter-6/put-it-together-4.tsx
- content/lessons/chapter-6/put-it-together-5.tsx
- content/lessons/chapter-6/put-it-together-6.tsx
We still use the boilerplate for in test vectors but eventually I would like to also display the inputs outputs and witnesses for every challenge
> Add code collapse to the rest of chapter 6

- components/Navbar/NavbarDesktop/Tab.tsx
- hooks/useLessonStatus.ts
This PR closes the first half of  #674 
Lock Icon no longer flashes
> Lock icon flash

- ui/lesson/ScriptingChallenge/Runner/index.tsx
>  Fit the play icon in the container on IOS

- ui/lesson/ScriptingChallenge/Runner/index.tsx
> Removed run script button from mobile info

- content/lessons/chapter-2/scripting-2.tsx
- content/lessons/chapter-4/address-2.tsx
- content/lessons/chapter-4/address-3.tsx
- content/lessons/chapter-4/public-key-3.tsx
- content/lessons/chapter-4/public-key-4.tsx
- content/lessons/chapter-5/derive-message-1.tsx
- content/lessons/chapter-5/validate-signature-1.tsx
- content/lessons/chapter-5/validate-signature-2.tsx
- content/lessons/chapter-5/validate-signature-3.tsx
- content/lessons/chapter-5/validate-signature-4.tsx
- content/lessons/chapter-5/verify-signature-2.tsx
- content/lessons/chapter-5/verify-signature-5.tsx
- content/lessons/chapter-6/in-out-4.tsx
- content/lessons/chapter-6/in-out-5.tsx
- content/lessons/chapter-6/put-it-together-1.tsx
- content/lessons/chapter-6/put-it-together-2.tsx
- content/lessons/chapter-6/put-it-together-3.tsx
- content/lessons/chapter-6/put-it-together-4.tsx
- content/lessons/chapter-6/put-it-together-5.tsx
- content/lessons/chapter-6/put-it-together-6.tsx
- ui/lesson/ScriptingChallenge/Editor.tsx
- ui/lesson/ScriptingChallenge/index.tsx
Closes #854 
also makes it possible to make the scripting challenge readonly for challenges where that is appropriate
> All Scripting Challenge lines now editable

- content/resources/chapter-7/index.ts
- content/resources/chapter-7/mempool-transaction.tsx
- content/resources/index.tsx
Adds the help pages for chapter 7
Needs javascript answer but can be merged asap
> Chapter 7 help pages

- content/resources/chapter-7/mempool-transaction.tsx
- ui/lesson/ScriptingChallenge/Editor.tsx
Adds the JS resources and makes them the Good enough answer, the user can try to reach th perfect answer on their own
also fixes another editor height error
[Preview](https://saving-satoshi-git-fork-benalleng-chapter-ab447a-savingsatoshi.vercel.app/en/chapters/chapter-7/mempool-transaction-1?dev=true)
> Add resources for JS in chapter 7

- yarn.lock
Been a year since we've started adding and removing packages to the yarn lock, decided to delete and reinstall to update oto see if there was a diff.
> Full refresh of yarn lock

- hooks/useDebounce.ts
- ui/lesson/ScriptingChallenge/Editor.tsx
- ui/lesson/ScriptingChallenge/index.tsx
- yarn.lock
I have a long term plan for how to get this working saving on the backend but for now this provides very close to the functionality we want.
> Save code as we go

- content/lessons/chapter-3/coop-3.tsx
- ui/common/Profile.tsx
Closes #865 
[Preview](https://saving-satoshi-git-fork-benalleng-issue865-savingsatoshi.vercel.app/en/chapters/chapter-3/coop-3?dev=true)
> Add chip in Coop-3

- content/lessons/chapter-2/intro-1.tsx
- content/lessons/chapter-2/intro-2.tsx
- content/lessons/chapter-4/address-3.tsx
- content/lessons/chapter-5/derive-message-7.tsx
- content/lessons/chapter-5/intro-3.tsx
- content/lessons/chapter-6/intro-2.tsx
- i18n/locales/en.ts
- ui/chapter/DesktopEnd.tsx
> Copy mistakes

- ui/common/Tooltip.tsx
Adds target blank that fixes a comment Christpoh mentioned
> Add target blank to tooltip

- content/lessons/chapter-2/mining-1.tsx
- i18n/locales/en.ts
- ui/common/HashFrequency.tsx
- ui/common/StartButton.tsx
Now uses a "100x" speed up to dramatically cut the length of the challenge
[Mining Challenge Preview](https://saving-satoshi-git-fork-benalleng-mining-c-72dcee-savingsatoshi.vercel.app/en/chapters/chapter-2/mining-1?dev=true)
This PR does NOT address any narrative inconsistencies in the mining challenge
> Speed up chapter 2 mining challenge

- components/HelpSuggestion.tsx
- i18n/locales/en.ts
- ui/lesson/Info.tsx
Closes #855 
@GBKS I think I've followed your design but would be good to get your eyes on this.   You can see an example of the component on [this preview link](https://saving-satoshi-git-fork-daviroo-highlight-5eeb17-savingsatoshi.vercel.app/en/chapters/chapter-4/address-2?dev=true).
> feat: Added help suggestion component

- ui/common/ContributionBar.tsx
- ui/lesson/HashrateChallenge.tsx
> Contribution Bar Width

- content/lessons/chapter-8/building-blocks-4.tsx
- content/lessons/chapter-8/intro-1.tsx
- content/lessons/chapter-8/intro-2.tsx
- content/lessons/chapter-8/intro-3.tsx
- i18n/locales/en.ts
> Chapter 8 Lesson 2

- content/lessons/chapter-8/building-blocks-4.tsx
- content/lessons/chapter-8/building-blocks-5.tsx
- i18n/locales/en.ts
> Chapter 8 Lesson 3

- ui/common/HolocatQuestion.tsx
> tooltip no longer nested link

- components/Navbar/NavbarDesktop/TabDesktop.tsx
> Navbar links use fully defined routes

- content/lessons/chapter-8/building-blocks-3.tsx
- content/lessons/chapter-8/building-blocks-4.tsx
- content/lessons/chapter-8/building-blocks-5.tsx
- content/lessons/chapter-8/building-blocks-6.tsx
- content/lessons/chapter-8/building-blocks-7.tsx
- i18n/locales/en.ts
- ui/common/CodeExample.tsx
> Chapter 8 lesson 5 (Validate Blocks)

- content/lessons/chapter-6/put-it-together-1.tsx
- i18n/locales/de.ts
- i18n/locales/en.ts
- i18n/locales/es.ts
I have some copy updates for chapters 1-5. I've been sitting on them, but after the feedback that came in earlier this week I figure it's good to get these merged  so nobody is doing duplicate work. Most of these are straightforward but I have comments for  changes that have additional context.
It's possible I might have to rebase after https://github.com/saving-satoshi/saving-satoshi/pull/931 is merged.
> Copy updates: chapters 1 - 5

- api/local/getProgress.ts
- api/progress/getProgress.ts
- app/[lang]/chapters/[slug]/[lesson]/page.tsx
- app/layout.tsx
- components/Hero.tsx
- components/Layout.tsx
- components/Modals/Account.tsx
- components/Modals/SignUp.tsx
- components/Navbar/NavbarDesktop/TabDesktop.tsx
- components/Navbar/NavbarMobile/TabMobile.tsx
- contexts/index.ts
- hooks/useSaveAndReturn.ts
- state/AuthFunctions.ts
- state/ProgressFunctions.ts
- state/state.ts
- ui/chapter/ChallengeListItem.tsx
- ui/chapter/Chapter.tsx
- ui/lesson/HashChallenge.tsx
- ui/lesson/ScriptingChallenge/index.tsx
- ui/lesson/TerminalChallenge.tsx
Marked as draft as I want to do a bit more testing.  I started this one a couple of weeks ago so some of the context on what I did is a little fuzzy.  @benalleng would appreciate if you could give it a test as well.
> chore: Moved progress state to jotai

- components/SignIn.tsx
fixes the build failure on dev
> use new progress context in SignIn

- content/lessons/chapter-8/building-blocks-3.tsx
- content/lessons/chapter-8/building-blocks-4.tsx
- content/lessons/chapter-8/building-blocks-5.tsx
- content/lessons/chapter-8/building-blocks-7.tsx
- content/lessons/chapter-8/building-blocks-8.tsx
- content/resources/chapter-8/building-blocks.tsx
- i18n/locales/en.ts
[preview link](https://saving-satoshi-8i0hkeqmb-savingsatoshi.vercel.app/)
> Chapter 8  lesson 6 ( Includes new class Declaration)

- content/lessons/chapter-4/public-key-3.tsx
- content/lessons/chapter-5/derive-message-7.tsx
- content/lessons/chapter-5/validate-signature-2.tsx
- content/lessons/chapter-5/verify-signature-2.tsx
- content/lessons/chapter-6/in-out-4.tsx
- content/lessons/chapter-6/intro-2.tsx
- content/lessons/chapter-8/building-blocks-8.tsx
- i18n/locales/en.ts
> Copy Functions colorcode

- i18n/locales/en.ts
Some minor updates to the copy in chapter 7. Tried my best to clarify some parts of the story. This also addresses https://github.com/saving-satoshi/saving-satoshi/issues/947
> Chapter 7: copy updates

- ui/lesson/ScriptingChallenge/Runner/index.tsx
fixes the terminal line replace error in chapter 8
[Preview](https://saving-satoshi-git-fork-benalleng-terminal-lines-savingsatoshi.vercel.app/en/chapters/chapter-8/building-blocks-3?dev=true)
> fix: terminal lines no-longer replace each other

- content/lessons/chapter-4/address-2.tsx
- content/lessons/chapter-4/address-3.tsx
- content/lessons/chapter-4/public-key-3.tsx
- content/lessons/chapter-5/validate-signature-1.tsx
- content/lessons/chapter-5/validate-signature-2.tsx
- content/lessons/chapter-5/verify-signature-5.tsx
- content/lessons/chapter-6/in-out-3.tsx
- content/lessons/chapter-6/in-out-4.tsx
- content/lessons/chapter-6/in-out-5.tsx
- content/lessons/chapter-6/put-it-together-1.tsx
- content/lessons/chapter-6/put-it-together-2.tsx
- content/resources/chapter-5/derive-message.tsx
- content/resources/chapter-6/put-it-together.tsx
- i18n/locales/en.ts
- styles/globals.css
https://docs.google.com/document/d/1ksMyK-PtV7x6xyLyECfcm3RuPP7NcrWMbIeweYmN7sw
> Addressing Satsies feedback: ch. 4-6

- content/lessons/chapter-4/address-2.tsx
- content/lessons/chapter-4/public-key-3.tsx
- content/resources/chapter-4/public-key.tsx
- i18n/locales/en.ts
Some updates to Chapter 4
http://localhost:3000/en/chapters/chapter-4/public-key-3/help
http://localhost:3000/en/chapters/chapter-4/public-key-3
I want to add a horizontal rule between lesson content and the challenge instructions. This could be a good candidate for abstracting out into a UI component (I don't know how to do this). For now I'm just using the `<hr>` tag.
On this page I also broke the hashing steps out into a numbered list. When I was gathering feedback for another project it was brought to my attention that anything you can do to visually break up blocks of text is generally going to be a win for the reader.
The generator point code sample is now more responsive
http://localhost:3000/en/chapters/chapter-4/public-key-3
> Chapter 4 updates

- content/lessons/chapter-6/put-it-together-1.tsx
- content/lessons/chapter-6/put-it-together-2.tsx
- ui/lesson/ScriptingChallenge/index.tsx
This PR closes #945 
Remove Regex for removing all comments and replaced it with regex to remove YOUR CODE HERE
> Removed and Replaced Regex

- content/lessons/chapter-8/building-blocks-3.tsx
- content/lessons/chapter-8/building-blocks-4.tsx
- content/lessons/chapter-8/building-blocks-5.tsx
- content/lessons/chapter-8/building-blocks-7.tsx
- content/lessons/chapter-8/building-blocks-8.tsx
- changed @0tuedon/bitcoin_rpcjs to @savingsatoshi/bitcoin_rpcjs
> Changed Bitcoin_rpcjs Libary name to savingsatoshi

- components/Modals/Help.tsx
- components/Navbar/NavbarMobile/Menu.tsx
- content/lessons/chapter-6/in-out-4.tsx
- content/lessons/chapter-6/in-out-5.tsx
- content/lessons/chapter-6/put-it-together-1.tsx
- content/lessons/chapter-6/put-it-together-2.tsx
- content/lessons/chapter-6/put-it-together-3.tsx
- content/lessons/chapter-7/mempool-transaction-1.tsx
- content/lessons/chapter-8/building-blocks-3.tsx
- content/lessons/chapter-8/building-blocks-6.tsx
- content/lessons/chapter-8/building-blocks-7.tsx
- content/lessons/chapter-8/building-blocks-8.tsx
- ui/chapter/ChallengeList.tsx
- ui/common/Tooltip.tsx
- ui/lesson/Info.tsx
> Swap overflow-scroll for overflow-auto thorugh codebase

- styles/globals.css
- ui/lesson/ScriptingChallenge/Editor.tsx
> Fix scripting challenge terminal height

- content/resources/chapter-2/hashing-2.tsx
- content/resources/chapter-2/hashing-4.tsx
- content/resources/chapter-2/hashing-6.tsx
- content/resources/chapter-2/mining-1.tsx
- content/resources/chapter-2/scripting-2.tsx
- i18n/locales/en.ts
- ui/common/CodeExample.tsx
Closes #969 
[Preview](https://saving-satoshi-git-fork-benalleng-chapter-2-help-savingsatoshi.vercel.app/en/chapters/chapter-2/intro-1?dev=true)
> chapter 2 help pages

- content/chapters/chapter-9/index.tsx
- content/lessons/chapter-9/index.tsx
- content/lessons/chapter-9/intro-1.tsx
- content/lessons/chapter-9/intro-2.tsx
- content/lessons/chapter-9/outro-1.tsx
- content/lessons/chapter-9/splits-1.tsx
- content/lessons/chapter-9/splits-2.tsx
- content/lessons/chapter-9/splits-3.tsx
- content/lessons/index.tsx
- i18n/locales/en.ts
- lib/progress.ts
> Created Lessons and Progress in chapter 9

- content/lessons/chapter-9/outro-1.tsx
- i18n/locales/en.ts
Closes #994 
Went freestyle with the copy for this one
[Preview](https://saving-satoshi-git-fork-benalleng-issue994-savingsatoshi.vercel.app/en/chapters/chapter-9/outro-1?dev=true)
> Add chapter 9 outro

- content/lessons/chapter-6/put-it-together-2.tsx
- i18n/locales/en.ts
This is a big challenge that requires a lot of steps so I broke it down to smaller pieces. 
Before:
https://savingsatoshi.com/en/chapters/chapter-6/put-it-together-2
After:
https://saving-satoshi-git-fork-satsie-ch-6-puttin-f0333e-savingsatoshi.vercel.app/en/chapters/chapter-6/put-it-together-2
> Chapter 6, put-it-together-2: Break instructions down to smaller steps

- content/lessons/chapter-7/mempool-transaction-1.tsx
- content/resources/chapter-7/mempool-transaction-1.tsx
- i18n/locales/en.ts
Closes #974
[Preview](https://saving-satoshi-git-fork-benalleng-issue974-savingsatoshi.vercel.app/en/chapters/chapter-7/mempool-transaction-1?dev=true)
> Chapter 7 resources update

- ui/common/StatusBar.tsx
reverts a change I think I let slip through that changed the text color of the status bar
> Text color change reverted from statusbar back to white

- content/lessons/chapter-6/hard/put-it-together-1.tsx
- content/lessons/chapter-6/hard/put-it-together-2.tsx
- content/lessons/chapter-6/hard/put-it-together-3.tsx
- content/lessons/chapter-6/hard/put-it-together-4.tsx
- content/lessons/chapter-6/hard/put-it-together-5.tsx
- content/lessons/chapter-6/hard/put-it-together-6.tsx
- content/resources/chapter-6/in-out-4-hard.tsx
- content/resources/chapter-6/index.ts
- content/resources/chapter-6/put-it-together-1-hard.tsx
- content/resources/chapter-6/put-it-together-1-normal.tsx
- content/resources/chapter-6/put-it-together-2-hard.tsx
- content/resources/chapter-6/put-it-together-2-normal.tsx
- content/resources/chapter-6/put-it-together-3-hard.tsx
- content/resources/chapter-6/put-it-together-3-normal.tsx
- content/resources/chapter-6/put-it-together-4-hard.tsx
- content/resources/chapter-6/put-it-together-5-hard.tsx
- content/resources/chapter-6/put-it-together-6-hard.tsx
- i18n/locales/en.ts
- state/progressState.ts
Begins the hardmode resources update and tweaks some copy from stale lessons
closes #973
[Preview](https://saving-satoshi-git-fork-benalleng-chapter-fa848b-savingsatoshi.vercel.app/en/chapters?dev=true#chapter-6)
> Update chapter 6 hardmode resources and tweak some stale lessons

- content/lessons/chapter-5/derive-message-7.tsx
> Chapter 5 Derive message 7 typo

- package.json
- ui/lesson/OpCodeChallenge/OpRunner.tsx
- yarn.lock
> feat: Added animation to script executor

- content/lessons/chapter-9/opcodes-10.tsx
- content/lessons/chapter-9/opcodes-5.tsx
- content/lessons/chapter-9/opcodes-6.tsx
- content/lessons/chapter-9/opcodes-8.tsx
- content/lessons/chapter-9/opcodes-9.tsx
- content/lessons/chapter-9/proposal-1.tsx
- content/lessons/chapter-9/proposal-2.tsx
- content/lessons/chapter-9/proposal-3.tsx
- i18n/locales/en.ts
- ui/lesson/OpCodeChallenge/OpRunner.tsx
- ui/lesson/OpCodeChallenge/index.tsx
- ui/lesson/OpCodeChallenge/runnerTypes.ts
Adds the first advanced challenge and the copy page before hand
> Advance challenge one

- content/lessons/chapter-4/public-key-3.tsx
Currently this link points to a private repo and users get a 404.
When do we anticipate the next release? If it's not for a while, should I make a PR to hot fix this to master?
> Chapter 4: fix secp256k1 lib 404

- content/lessons/chapter-3/coop-1.tsx
- content/lessons/chapter-3/pool-1.tsx
- content/lessons/chapter-5/validate-signature-4.tsx
- i18n/locales/en.ts
We're doing a full review of the story and I caught some minor copy errors. In a week or two expect a PR with more story updates.
> Misc copy fixes

- content/lessons/chapter-9/proposal-4.tsx
- i18n/locales/en.ts
- ui/common/StatusBar.tsx
- ui/lesson/OpCodeChallenge/LanguageExecutor.ts
- ui/lesson/OpCodeChallenge/OPFunctions.ts
- ui/lesson/OpCodeChallenge/OpRunner.tsx
Adds the last challenge for chapter 9!
[Preview](https://saving-satoshi-git-fork-benalleng-advanced-97cd53-savingsatoshi.vercel.app/en/chapters/chapter-9/proposal-4?dev=true)
> Advanced challenge three

- hooks/useEnvironment.ts
- i18n/locales/en.ts
Fixes an error where environment thinks that savingsatoshi dev environments are prod and some stray typos
> Typos and Environment Error

- content/lessons/chapter-6/normal/in-out-4.tsx
Fix for a bug noticed by @satsie where this lesson wasn't showing on normal mode for chapter 6.
> fix: Fixed lesson key for CH6INO4_NORMAL

- components/SignIn.tsx
- state/AuthFunctions.ts
- state/progressState.ts
Fixed a bug noticed by @satsie where progress would be reverted to default when switching between 2 different accounts.
> fix: Fixed logout progress loss bug

- content/lessons/chapter-6/hard/in-out-4.tsx
- content/lessons/chapter-6/normal/put-it-together-1.tsx
- i18n/locales/en.ts
Closes #1069 and closes #1072 
also addresses #1070
> Fix stale translations for chapter 6

- content/chapters/chapter-10/index.tsx
- content/lessons/chapter-10/index.tsx
- content/lessons/chapter-10/intro-1.tsx
- content/lessons/chapter-10/intro-2.tsx
- content/lessons/chapter-10/making-a-payment-1.tsx
- content/lessons/chapter-10/making-a-payment-2.tsx
- content/lessons/chapter-10/making-a-payment-3.tsx
- content/lessons/chapter-10/making-a-payment-4.tsx
- content/lessons/chapter-10/making-a-payment-5.tsx
- content/lessons/chapter-10/opening-a-channel-1.tsx
- content/lessons/chapter-10/opening-a-channel-2.tsx
- content/lessons/chapter-10/opening-a-channel-3.tsx
- content/lessons/chapter-10/opening-a-channel-4.tsx
- content/lessons/chapter-10/opening-a-channel-5.tsx
- content/lessons/chapter-10/outro-1.tsx
- content/lessons/index.tsx
- content/resources/chapter-9/proposal-3.tsx
- i18n/locales/en.ts
- state/progressState.ts
> Chap 10 scaffold

- i18n/locales/en.ts
Fixes for a few typos I encountered while looking at some chapter 6 hard mode stuff.
> Chapter 6: fix typos

- i18n/locales/en.ts
This PR contains story updates that have been made for chapters 1 and 2.
> Story updates: chapters 1 and 2

- content/chapters/chapter-3/index.tsx
- content/lessons/chapter-5/intro-2.tsx
- content/lessons/chapter-5/intro-3.tsx
- content/lessons/chapter-5/verify-signature-2.tsx
- i18n/locales/en.ts
This PR contains story updates for chapters 3, 4, and 5.
> Story updates: chapters 3, 4, 5

- content/chapters/chapter-1/index.tsx
- content/chapters/chapter-2/index.tsx
- content/chapters/chapter-3/index.tsx
- content/chapters/chapter-4/index.tsx
- content/chapters/chapter-5/index.tsx
- content/lessons/chapter-6/intro-1.tsx
- content/lessons/chapter-6/intro-2.tsx
- content/lessons/chapter-7/intro-2.tsx
- content/lessons/chapter-8/building-blocks-1.tsx
- content/lessons/chapter-8/building-blocks-2.tsx
- i18n/locales/en.ts
This PR has story updates for chapters 6, 7, and 8, as well as a few misc updates. There's one more screen in chapter 8 I need to update but will do it in a future PR.
Some notable changes:
- Mike Ramen is now Mika 3000
- We are now using common noun/lowercase formatting for "bitcoin"
- Made paragraph breaks on the chapter overview page more defined (increased tailwind top margin from `mt-2` to `mt-8`)
> Story updates: chapters 6, 7, 8

- content/lessons/chapter-4/address-3.tsx
> CH4 Address 2 Bech32.js broken link

- content/lessons/chapter-9/proposal-3.tsx
- content/lessons/chapter-9/proposal-4.tsx
- ui/lesson/OpCodeChallenge/OpFunctions.ts
- ui/lesson/OpCodeChallenge/OpRunner.tsx
- ui/lesson/OpCodeChallenge/index.tsx
- ui/lesson/OpCodeChallenge/runnerTypes.ts
Fixes a bug where the initial stack could be formatted incorrectly and it would not be caught by getSig() and getKey()
> Opchecksig regex

- components/Navbar/Address.tsx
- components/Navbar/NavbarDesktop/NavbarDesktop.tsx
- components/Navbar/NavbarMobile/NavbarMobile.tsx
- ui/common/StatusBar.tsx
- ui/lesson/Info.tsx
Fixes some sizing issues for mobile on the navbar and status bar
> Navbar and Statusbar sizing

- content/resources/chapter-9/opcodes-10.tsx
- content/resources/chapter-9/opcodes-5.tsx
- content/resources/chapter-9/opcodes-6.tsx
- content/resources/chapter-9/opcodes-8.tsx
- content/resources/chapter-9/opcodes-9.tsx
- content/resources/chapter-9/proposal-2.tsx
- content/resources/chapter-9/proposal-3.tsx
- content/resources/chapter-9/proposal-4.tsx
- i18n/locales/en.ts
- ui/common/ResourcePage.tsx
Closes #1046 
adds some reading resources and tips for chapter 9
> Finalize chapter 9 resources

- content/lessons/chapter-3/split-2.tsx
- ui/lesson/HashrateChallenge.tsx
Initially intended as a resource page branch I am just fixing some styling errors on chapter 3
[Preview](https://saving-satoshi-git-fork-benalleng-chapter-3-help-savingsatoshi.vercel.app/en/chapters/chapter-3/split-2?dev=true)
> Cleanup chapter 3 typo and styling

- components/Modals/Modal.tsx
> Allow modal scrolling on overflow

- content/lessons/chapter-10/intro-2.tsx
- content/lessons/chapter-3/split-2.tsx
- i18n/locales/en.ts
- shared/SignatureButton.tsx
- shared/icons/ArrowRightLarge.tsx
- shared/icons/Hyperlink.tsx
- shared/icons/WhiteCheck.tsx
- ui/lesson/HashrateChallenge.tsx
- ui/lesson/TransactionsChallenge/OutputScript.tsx
- ui/lesson/TransactionsChallenge/Tab.tsx
- ui/lesson/TransactionsChallenge/Tabs.tsx
- ui/lesson/TransactionsChallenge/index.tsx
- utils/data.ts
[preview](https://saving-satoshi-git-fork-0tuedon-chap-10-ch-d0aa62-savingsatoshi.vercel.app/en/chapters/chapter-10/intro-2?dev=true)
> Chapter 10 Challenge component

- content/lessons/chapter-3/split-2.tsx
- i18n/locales/en.ts
This PR addresses issue https://github.com/saving-satoshi/saving-satoshi/issues/1111. I was happily surprised that fixing it only required a few small changes.
> Chapter 3: Fix mining reward amount

- components/SignIn.tsx
Fixes an issue where take me to where I left off leads to a null lesson
> Take me to where I left off currentLessonNull catch

- i18n/locales/en.ts
- ui/chapter/Intro.tsx
- ui/lesson/OpCodeChallenge/Runner/index.tsx
Fixes #1100 
- padding fix
- switch to execute tab on mobile when running script
- came up with alternative advance challenge heading
> Chapter 9 feedback fixes

- content/chapters/chapter-10/index.tsx
- content/lessons/chapter-10/making-a-payment-2.tsx
- content/lessons/chapter-10/making-a-payment-3.tsx
- content/lessons/chapter-10/making-a-payment-5.tsx
- content/lessons/chapter-10/making-a-payment-6.tsx
- content/lessons/chapter-10/making-a-payment-7.tsx
- content/lessons/chapter-10/opening-a-channel-1.tsx
- content/lessons/chapter-10/opening-a-channel-2.tsx
- content/lessons/chapter-10/opening-a-channel-3.tsx
- content/lessons/chapter-10/opening-a-channel-4.tsx
- content/lessons/chapter-10/opening-a-channel-5.tsx
- content/lessons/chapter-10/updating-the-state-1.tsx
- content/lessons/chapter-10/updating-the-state-2.tsx
- content/lessons/chapter-10/updating-the-state-3.tsx
- content/lessons/chapter-10/updating-the-state-4.tsx
- content/lessons/chapter-10/updating-the-state-5.tsx
- content/lessons/chapter-10/updating-the-state-6.tsx
- ui/lesson/TransactionsChallenge/OutputScript.tsx
- ui/lesson/TransactionsChallenge/index.tsx
Finalizes the copy for chapter 10
[Preview](https://saving-satoshi-git-fork-benalleng-copy-fix-71f9fc-savingsatoshi.vercel.app/en/chapters/chapter-10/intro-1?dev=true)
> Background colors chapter 10

- ui/common/StatusBar.tsx
- ui/lesson/ScriptingChallenge/Runner/index.tsx
- ui/lesson/Terminal.tsx
This follows on #1122 to also switch tabs on pressing run for the scripting challenges
also adds 2 small taliwind fixes with the statusbar
> Scripting challenge tab change

- content/chapters/chapter-9/index.tsx
- content/lessons/chapter-9/intro-2.tsx
- content/lessons/chapter-9/opcodes-8.tsx
- content/lessons/chapter-9/proposal-4.tsx
- i18n/locales/en.ts
This PR contains story updates to chapter 9. The main change is the donations are no longer being shared with Vanderpoole, they are instead going to a charity he selected: the Lil Bits Foundation, a non-profit dedicated to helping children. 
I kept the exercises as-is with `PUBKEY(VANDERPOOLE)` and `SIG(VANDERPOOLE)` because 1. `PUBKEY(LILBITSFOUNDATION)` is a mouthful (maybe `PUBKEY(LILBITS)` is better?), 2. I think it's safe to assume that Vanderpoole is responsible for distributing the funds, especially because it was announced on live TV (I added a sentence to address this).
> copy: ch 9 story updates

- content/lessons/chapter-3/coop-1.tsx
- content/lessons/chapter-3/coop-3.tsx
- content/lessons/chapter-3/pool-1.tsx
- content/lessons/chapter-3/pool-2.tsx
- content/lessons/chapter-3/split-2.tsx
- i18n/locales/en.ts
This PR contains a bunch of updates that hopefully clarify the mining storyline and fill in any holes. A noteworthy change is we are trying to move away from calling our friends "pool operators" and instead calling them miners, because the former implies a solution where we have to make a a pool of pools and that is confusing.
> copy: clarifications for the mining storyline

- content/lessons/chapter-5/validate-signature-1.tsx
- content/lessons/chapter-8/building-blocks-8.tsx
> Save data key for CH8BBK8

- content/lessons/chapter-10/intro-1.tsx
- content/lessons/chapter-10/intro-2.tsx
- content/lessons/chapter-10/intro-3.tsx
- content/lessons/chapter-10/making-a-payment-4.tsx
- i18n/locales/en.ts
This PR contains story updates that have been made to chapter 10.
> copy: ch10 story updates

- i18n/locales/en.ts
This PR contains minor copy updates for chapter 10.
> copy: minor updates to ch10 outro

- content/lessons/chapter-10/making-a-payment-2.tsx
- content/lessons/chapter-10/making-a-payment-5.tsx
- content/lessons/chapter-10/making-a-payment-6.tsx
- content/lessons/chapter-10/making-a-payment-8.tsx
- content/resources/chapter-10/index.ts
- content/resources/chapter-10/making-a-payment-2.tsx
- content/resources/chapter-10/making-a-payment-5.tsx
- content/resources/chapter-10/making-a-payment-8.tsx
- content/resources/chapter-10/opening-a-channel-2.tsx
- content/resources/chapter-10/opening-a-channel-4.tsx
- content/resources/chapter-10/updating-the-state-1.tsx
- content/resources/chapter-10/updating-the-state-3.tsx
- content/resources/chapter-10/updating-the-state-5.tsx
- content/resources/index.tsx
- i18n/locales/en.ts
- shared/SignatureButton.tsx
- ui/lesson/TransactionsChallenge/index.tsx
Adds the resources for chapter 10
> Chapter 10 resources

- ui/lesson/OpCodeChallenge/OpRunner.tsx
- ui/lesson/TransactionsChallenge/OutputScript.tsx
- ui/lesson/TransactionsChallenge/index.tsx
> Adds error handler on the runner for chapter 10

- ui/lesson/TransactionsChallenge/OutputScript.tsx
This PR should fix #1167
https://github.com/user-attachments/assets/73c84fb9-f52f-438c-a91b-d3c8e72a53fa
> Safari break issue

- content/lessons/chapter-10/making-a-payment-1.tsx
- content/lessons/chapter-10/making-a-payment-5.tsx
- content/lessons/chapter-10/opening-a-channel-2.tsx
- content/lessons/chapter-10/updating-the-state-1.tsx
- content/lessons/chapter-10/updating-the-state-3.tsx
- i18n/locales/en.ts
This PR contains many copy and design updates that came out of [Christoph's chapter 10 QA](https://www.figma.com/design/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=9670-3299). It's not all of them, but it gets the smaller stuff out of the way.
> ch 10 design and copy updates

- i18n/locales/en.ts
- styles/globals.css
- ui/lesson/TransactionsChallenge/index.tsx
Closes #1188
fee reminder copy update and use css class to move magic numbers on challenge container
> Fee reminder

- content/lessons/chapter-10/opening-a-channel-4.tsx
- i18n/locales/en.ts
fixes some translation text wrapping on the initial stack spans
> Tanslation wrapping

- content/lessons/chapter-10/opening-a-channel-2.tsx
- content/lessons/chapter-10/opening-a-channel-4.tsx
- content/resources/chapter-10/making-a-payment-8.tsx
- content/resources/chapter-10/opening-a-channel-2.tsx
- content/resources/chapter-10/opening-a-channel-4.tsx
- content/resources/chapter-10/updating-the-state-1.tsx
- content/resources/chapter-10/updating-the-state-3.tsx
- content/resources/chapter-10/updating-the-state-5.tsx
- i18n/locales/en.ts
- ui/lesson/TransactionsChallenge/index.tsx
This PR contains updates I've made after doing QA on the first two parts of chapter 10 ("Celebration" and "The initial funds"). It's mostly copy changes in an effort to clarify some instructions. I will have more updates to chapter 10 in a future PR.
> ch10: misc updates based on qa

- content/lessons/chapter-10/updating-the-state-1.tsx
- content/lessons/chapter-10/updating-the-state-3.tsx
- content/lessons/chapter-10/updating-the-state-6.tsx
- i18n/locales/en.ts
- i18n/locales/pt.ts
- utils/data.ts
More ch 10 QA updates that have been sitting in my fork for a while as I've waited for the upstream PR to be merged. This got prior approval from @pinheadmz here: https://github.com/satsie/saving-satoshi/pull/1
> ch10 - misc qa based updates

- ui/lesson/TransactionsChallenge/index.tsx
> Commitment name before aymmetry is explained

- content/lessons/chapter-10/making-a-payment-1.tsx
- content/lessons/chapter-10/making-a-payment-2.tsx
- content/lessons/chapter-10/making-a-payment-5.tsx
- content/lessons/chapter-10/making-a-payment-6.tsx
- content/lessons/chapter-10/making-a-payment-8.tsx
- i18n/locales/en.ts
These are some updates I made after QA'ing "The refund" section of chapter 10 last week. I played through the updated final challenge and it looks good to me. Everything works as expected. Nice touch that the hints refresh when you go from working on Laszlo's commitment transaction to yours.
> ch 10: qa updates to part 3, the refund

- components/Fonts.tsx
- components/Hero.tsx
- shared/Boss.tsx
- styles/globals.css
- tailwind.config.js
Adds the Chaincode Boss banner as a link to the application page
> Boss banner

- ui/lesson/TransactionsChallenge/OutputScript.tsx
- ui/lesson/TransactionsChallenge/index.tsx
> Checksig error catch

- ui/chapter/Intro.tsx
Closes #1230 
[Preview](https://saving-satoshi-git-fork-benalleng-chrome-i-e3b037-savingsatoshi.vercel.app/en/chapters/chapter-9/opcodes-1?dev=true)
> Chrome intro style regression

- ui/chapter/Intro.tsx
> Polish centering fro chrome and firefox

- styles/globals.css
Closes #1199 
[Chapters page](https://saving-satoshi-git-fork-benalleng-chrome-s-f81137-savingsatoshi.vercel.app/en/chapters)
[Chapter 9 where there can be a lot of scrollbars](https://saving-satoshi-git-fork-benalleng-chrome-s-f81137-savingsatoshi.vercel.app/en/chapters/chapter-9/opcodes-5?dev=true)
> Try some new chrome scrollbars

- ui/lesson/ScriptingChallenge/Runner/Terminal.tsx
- ui/lesson/ScriptingChallenge/Runner/index.tsx
- ui/lesson/ScriptingChallenge/index.tsx
I added a new error catch in the websocket connection to make sure we are always displaying an error if the websocket doesn't receive a payload before closing. As well as some minor styling fixes for mobile
> Websocket error catching

- content/lessons/chapter-2/scripting-2.tsx
- i18n/locales/en.ts
- ui/common/StatusBar.tsx
- ui/lesson/ScriptingChallenge/Runner/index.tsx
- ui/lesson/TransactionsChallenge/index.tsx
Fixes an error in the browser tab title with a missing translation key and fixes a regression from the I'm stuck button and the Try again button in chapter 7
> Missing translation key and fix try again im stuck discrepency

- components/Hero.tsx
Do not merge on prod till January 1st 2025
> Queued Boss banner removal

- app/[lang]/about/page.tsx
- content/lessons/chapter-10/making-a-payment-2.tsx
- content/lessons/chapter-10/making-a-payment-5.tsx
- i18n/config.ts
- i18n/locales/en.ts
- i18n/locales/fr.ts
- i18n/locales/index.ts
- public/.well-known/nostr.json
- ui/lesson/TransactionsChallenge/index.tsx
Merge dev into master to cut the v1.10.5 release which includes an update to make chapter 10 non-alcoholic (at least in the English version :smiley: )
> v1.10.5 - Remove alcohol from chapter 10

- i18n/locales/pt.ts
This PR significantly expands and updates the **Portuguese** translation for the project's "About" page, located in [i18n/locales/pt.ts](https://github.com/saving-satoshi/saving-satoshi/blob/dev/i18n/locales/pt.ts)
The previous translation was a brief, two-paragraph summary. This update replaces it with a comprehensive translation that mirrors the full English content. This includes:
- A new, more engaging title and introduction (The previous title was not correctly translated).
- A detailed explanation of the project's philosophy and target audience (Which was not translated into Portuguese).
- Links for users to join the community on GitHub, Discord, X (Twitter), Nostr, and Bluesky.
**Motivation:**
The goal is to achieve content parity between the English and Portuguese versions of the …
> Update Portuguese project description
